import type { Metadata } from "next";

import type {
  KaomojiCollectionGroup,
  KaomojiFaqProps,
  KaomojiHeroProps,
  KaomojiWhatProps,
  KaomojiWhyProps,
} from "@/features/kaomoji/types";

import { withCanonical } from "@/lib/seo";

export const metadata: Metadata = {
  title: "豚顔文字一覧（Kaomoji）｜(๑•(oo)•๑)・ブヒブヒもコピペ",
  description:
    "豚顔文字（Kaomoji）をまとめて掲載。かわいい豚、シンプル豚、表情豊か、アクション、特殊・ブヒブヒ、装飾、ユニーク、AA風まで。検索＆ワンクリックでコピーして、LINE/X（Twitter）/Instagram/Discordにそのままコピペ。登録不要で無料。スマホでもOK。",
  ...withCanonical("/buta-kaomoji"),
};

export const butaKaomojiHeroContent: KaomojiHeroProps = {
  title: "豚顔文字一覧",
  kaomoji: "(๑•(oo)•๑)  ^(oo)^",
  subtitle: "かわいい豚からAA風まで【コピペ簡単】",
  description:
    "鼻（oo）や丸い輪郭で“ぶた感”を出す豚顔文字を集めました。しょんぼり・怒り・ドヤ・アクションなど、表情の幅も意外と広め。気に入った顔文字はワンクリックでコピーして、そのまま貼り付けできます。",
  primaryCta: { href: "#list", label: "顔文字を探す" },
  secondaryCta: { href: "/", label: "ホームへ" },
};

export const butaKaomojiWhatContent: KaomojiWhatProps = {
  heading: "豚顔文字（Kaomoji）とは？",
  intro:
    "豚顔文字は、豚の鼻（oo）や耳、丸い顔つきを文字で表現したKaomojiです。かわいさだけでなく、ユニークさやネタ感も出しやすく、会話を和ませたいときに便利です。",
  usageHeading: "使えるシーン",
  usageItems: [
    "かわいい雰囲気を足したいとき",
    "ネタっぽくリアクションしたいとき",
    "食べ物・料理（豚）関連の話題に",
    "表情で気分を伝えたいとき（しょんぼり/怒り/ドヤ等）",
    "SNS投稿の一言にアクセントを付けたいとき",
  ],
  typesHeading: "豚顔文字の種類",
  types: [
    {
      title: "かわいい豚",
      description: "丸くて優しい雰囲気。日常会話に合わせやすい。",
      example: "例: (๑•(oo)•๑)  (・(oo)・)",
    },
    {
      title: "シンプル豚",
      description: "短くて使いやすい。文字化けが心配なときにも。",
      example: "例: ^(oo)^  (oo)",
    },
    {
      title: "表情豊か",
      description: "喜怒哀楽のバリエーションで、ニュアンスを出せます。",
      example: "例: (｀(oo)´)  (｡•(oo)•｡)",
    },
    {
      title: "アクション",
      description: "動きやしぐさで、会話のテンポを作りたいときに。",
      example: "例: (oo)ﾉｼ  (oo)ﾀﾞｯ",
    },
    {
      title: "特殊・ブヒブヒ",
      description: "ブヒブヒ系や装飾でネタ感強め。",
      example: "例: (´(oo)`)ﾌﾞﾋ  (oo)ﾌﾞﾋﾌﾞﾋ",
    },
  ],
  featuresHeading: "豚っぽさが出るパーツ",
  features: [
    { symbol: "oo", title: "鼻", description: "豚の特徴そのもの。入れるだけで豚っぽさが出ます。" },
    { symbol: "( )", title: "丸い輪郭", description: "ふっくらした顔の雰囲気を作れます。" },
    { symbol: "^", title: "耳", description: "耳を表現して、動物感を強められます。" },
    { symbol: "ﾌﾞﾋ", title: "鳴き声", description: "ネタや主張に使いやすいアクセント。" },
  ],
};

export const butaKaomojiWhyContent: KaomojiWhyProps = {
  heading: "豚顔文字の使い分け",
  subheading: "かわいくも、ネタにも。豚顔文字は温度調整がしやすい。",
  guideHeading: "シーン別ガイド",
  guides: [
    {
      title: "日常の返信",
      bullets: ["かわいい豚で柔らかい雰囲気に", "短文 + 顔文字が自然"],
      recommend: "おすすめ: (๑•(oo)•๑)  ^(oo)^",
    },
    {
      title: "ネタ・冗談",
      bullets: ["ブヒブヒ系で遊び心を出す", "使いすぎると読みにくいので控えめに"],
      recommend: "おすすめ: (´(oo)`)ﾌﾞﾋ  (oo)ﾌﾞﾋﾌﾞﾋ",
    },
    {
      title: "気分を表情で",
      bullets: ["表情カテゴリでニュアンスを選ぶ", "怒り/しょんぼり/ドヤなど使い分け"],
      recommend: "おすすめ: (｀(oo)´)  (｡•(oo)•｡)",
    },
    {
      title: "SNS投稿",
      bullets: ["装飾やAA風で見た目を盛る", "写真や絵文字と合わせると映える"],
      recommend: "おすすめ: (V −(●●)−V)  <(^oo^)>",
    },
  ],
  cultureHeading: "“ぶた感”は会話のスパイス",
  cultureBody:
    "豚顔文字は、可愛さとユーモアを同時に出せるのが強み。ちょっとしたリアクションに添えるだけで、会話が軽くなって返しやすくなります。",
  cultureCards: [
    { title: "かわいい", description: "ゆるい空気を作りやすい。" },
    { title: "ネタ", description: "ブヒブヒで遊べる。" },
    { title: "表情", description: "喜怒哀楽の幅が意外と広い。" },
  ],
  tipsHeading: "すぐ使える例文",
  tips: [
    {
      title: "返信に添える",
      body: "短い文に1つ足すだけで、雰囲気がやわらぎます。",
      example: "例: 了解！ (๑•(oo)•๑)",
    },
    {
      title: "ネタにする",
      body: "冗談っぽく言いたいときに。",
      example: "例: それはブヒ… (´(oo)`)ﾌﾞﾋ",
    },
    {
      title: "気分を出す",
      body: "表情でニュアンスを足したいときに。",
      example: "例: 今日はちょい怒 (｀(oo)´)",
    },
  ],
};

export const butaKaomojiFaqContent: KaomojiFaqProps = {
  heading: "よくある質問（FAQ）",
  subheading: "豚顔文字、迷ったらここだけ見ればOK。",
  items: [
    {
      question: "豚顔文字はどうやってコピーできますか？",
      answer:
        "一覧から好きな豚顔文字をクリックするとコピーできます。あとはLINEやSNSなどに貼り付けるだけです。",
    },
    {
      question: "文字化けしにくいのはどれ？",
      answer:
        "環境によっては特殊文字の見え方が変わることがあります。心配なときは、シンプル豚（^(oo)^ など）を選ぶと安心です。",
    },
    {
      question: "ブヒブヒ系はどんなときに使う？",
      answer:
        "ネタっぽい返事や、軽いツッコミに便利です。会話の空気を重くしたくないときに役立ちます。",
    },
    {
      question: "タグは何のためにありますか？",
      answer:
        "検索用の目印です。『かわいい』『表情』『AA風』などで絞り込んで探せます。",
    },
  ],
};

export const butaKaomojiGroups: KaomojiCollectionGroup[] = [
  {
    title: "かわいい豚",
    items: [
      { kaomoji: "🐷₍ᐢ･⚇･ᐢ₎", tags: ["可愛い","豚","ぶひ"] },
      { kaomoji: "🐽(՞•🐽•՞)", tags: ["可愛い","豚","鼻"] },
      { kaomoji: "🐷( ˘•🐽•˘ )", tags: ["可愛い","豚","ほんわか"] },
      { kaomoji: "🐖(๑•🐽•๑)", tags: ["可愛い","豚","キラキラ"] },
      { kaomoji: "🐷ฅ՞^🐽^՞ฅ", tags: ["可愛い","豚","手"] },
      { kaomoji: "(੭՞•🐽•՞)੭🐷", tags: ["可愛い","豚","応援"] },
      { kaomoji: "🐖( ˙Ꙫ˙ )", tags: ["可愛い","豚","まん丸"] },
      { kaomoji: "🐽(̂•͈Ꙫ•͈)̂", tags: ["可愛い","豚","ニコニコ"] },
      { kaomoji: "🐷ʚ ᐢ･⚇･ᐢ ɞ", tags: ["可愛い","豚","天使"] },
      { kaomoji: "(๑• 🐽 •๑)ﾌﾞ-", tags: ["可愛い","豚","ブヒ"] },
      { kaomoji: "🐖ෆෆ(•̀🐽•̀)ෆෆ", tags: ["可愛い","豚","ハート"] },
      { kaomoji: "🐷(̂•͈Ꙫ•͈)̂ﾌﾞｩ♡", tags: ["可愛い","豚","ラブ"] },
      { kaomoji: "🐽⍝◜ᐢ•⚇•ᐢ◝⍝", tags: ["可愛い","豚","まる"] },
      { kaomoji: "🐷( * ˙🐽˙ * )", tags: ["可愛い","豚","キラキラ"] },
      { kaomoji: "🐖( ˙🐽˙ )ᐝ", tags: ["可愛い","豚","ぽんぽん"] },
      { kaomoji: "🐷(･🐽･)", tags: ["可愛い","豚","シンプル"] },
      { kaomoji: "🐽(^🐽^)", tags: ["可愛い","豚","笑顔"] },
      { kaomoji: "🐖(o'🐽'o)", tags: ["可愛い","豚","まる目"] },
      { kaomoji: "🐷(・🐽・)", tags: ["可愛い","豚","普通"] },
      { kaomoji: "🐽( ˘•🐽•˘ )🐖", tags: ["可愛い","豚","友達"] },
      { kaomoji: "🐷🐷( ˙꒳˙ )", tags: ["可愛い","豚","仲間"] },
      { kaomoji: "🐖(･ω･ )", tags: ["可愛い","豚","のんびり"] },
      { kaomoji: "🐽( ˘ω˘ )", tags: ["可愛い","豚","満足"] },
      { kaomoji: "🐷٩(˘ω˘)۶", tags: ["可愛い","豚","やった"] },
      { kaomoji: "🐖(˶‾᷄꒳‾᷅˵)", tags: ["可愛い","豚","照れ"] },
      { kaomoji: "🐷(ᴖ‿ᴖ)", tags: ["可愛い","豚","嬉しい"] },
      { kaomoji: "🐽(⌒▽⌒)", tags: ["可愛い","豚","ニコニコ"] },
      { kaomoji: "🐖(｡•́‿•̀｡)", tags: ["可愛い","豚","楽しい"] },
      { kaomoji: "🐷( ◠‿◠ )", tags: ["可愛い","豚","穏やか"] },
      { kaomoji: "🐽ᕕ( ˘ω˘ )ᕗ", tags: ["可愛い","豚","元気"] },
    ],
  },
  {
    title: "シンプル豚",
    items: [
      { kaomoji: "₍ᐢ･⚇･ᐢ₎", tags: ["シンプル","豚","基本"] },
      { kaomoji: "( ˙Ꙫ˙ )", tags: ["シンプル","豚","まる"] },
      { kaomoji: "(^🐽^)", tags: ["シンプル","豚","笑顔"] },
      { kaomoji: "( ˘•🐽•˘ )", tags: ["シンプル","豚","可愛い"] },
      { kaomoji: "(՞•Ꙫ• ՞)", tags: ["シンプル","豚","普通"] },
      { kaomoji: "₍ᐢ.⚇.ᐢ₎", tags: ["シンプル","豚","まる"] },
      { kaomoji: "₍•̀ ⚇•́ ₎", tags: ["シンプル","豚","キリッ"] },
      { kaomoji: "₍◎⚇◎₎", tags: ["シンプル","豚","まる目"] },
      { kaomoji: "( ´🐽`)", tags: ["シンプル","豚","普通"] },
      { kaomoji: "(･🐽･)", tags: ["シンプル","豚","基本"] },
      { kaomoji: "( ˙🐽˙ )", tags: ["シンプル","豚","まる"] },
      { kaomoji: "(•͈⚇•͈)", tags: ["シンプル","豚","可愛い"] },
      { kaomoji: "₍ᐢ`🐽´ᐢ₎", tags: ["シンプル","豚","ぷんぷん"] },
      { kaomoji: "₍ᐢ◞⚇◟ᐢ₎", tags: ["シンプル","豚","困る"] },
      { kaomoji: "₍ᐢ•̀ ⚇•́ ᐢ₎", tags: ["シンプル","豚","真剣"] },
      { kaomoji: "₍ᐢ꩜⚇꩜ᐢ₎", tags: ["シンプル","豚","キラキラ"] },
      { kaomoji: "₍ᐢㅎ⚇ㅎᐢ₎", tags: ["シンプル","豚","ニコニコ"] },
      { kaomoji: "('⚇')", tags: ["シンプル","豚","基本"] },
      { kaomoji: "( * ˙🐽˙ * )", tags: ["シンプル","豚","キラキラ"] },
      { kaomoji: "( ˙🐽˙ )ᐝ", tags: ["シンプル","豚","ぽんぽん"] },
      { kaomoji: "( •🐽• )", tags: ["シンプル","豚","普通"] },
      { kaomoji: "( — 🐽 — )", tags: ["シンプル","豚","無表情"] },
      { kaomoji: "( ´- 🐽 -)", tags: ["シンプル","豚","静か"] },
      { kaomoji: "(//// 🐽 ////)", tags: ["シンプル","豚","照れ"] },
      { kaomoji: "(υ◉🐽◉υ)", tags: ["シンプル","豚","驚き"] },
    ],
  },
  {
    title: "表情豊か",
    items: [
      { kaomoji: "(´・(oo)・｀)", tags: ["表情","豚","困る"] },
      { kaomoji: "(￣(oo)￣)", tags: ["表情","豚","普通"] },
      { kaomoji: "(；ﾟ(OO)ﾟ)", tags: ["表情","豚","驚き"] },
      { kaomoji: "｡ﾟ(ﾟ´(00)`ﾟ)ﾟ｡", tags: ["表情","豚","泣く"] },
      { kaomoji: "(*'(OO)'*)", tags: ["表情","豚","嬉しい"] },
      { kaomoji: "(V´｡(oo)｡｀V)", tags: ["表情","豚","照れ"] },
      { kaomoji: "(V｀⚇´V)", tags: ["表情","豚","怒る"] },
      { kaomoji: "(͒˶´⚇`˵)͒", tags: ["表情","豚","ぷんぷん"] },
      { kaomoji: "(͒ ›Ꙫ‹ )͒୭♡", tags: ["表情","豚","ラブ"] },
      { kaomoji: "(´♡♡(oo)♡｀)", tags: ["表情","豚","愛"] },
      { kaomoji: "(▽-(00)-▽)♡", tags: ["表情","豚","ハート"] },
      { kaomoji: "(´Φ(oo)Φ｀)", tags: ["表情","豚","じっと"] },
      { kaomoji: "(∩◕(oo)◕∩)", tags: ["表情","豚","可愛い"] },
      { kaomoji: "(՞◕ Ꙫ ◕՞)", tags: ["表情","豚","キラキラ"] },
      { kaomoji: "(◕🐽◕)", tags: ["表情","豚","まる目"] },
      { kaomoji: "( ͡ ͡° ͜ 🐽 ͡ ͡°)", tags: ["表情","豚","ニヤニヤ"] },
      { kaomoji: "( ͡σ ͜ 🐽 σ)", tags: ["表情","豚","いたずら"] },
      { kaomoji: "(੭◎^ 🐽 ^◎ )੭", tags: ["表情","豚","応援"] },
      { kaomoji: "(๑ˊ◉🐽◉๑)", tags: ["表情","豚","キラキラ"] },
      { kaomoji: "(⦁᳐🐽⦁᳐)", tags: ["表情","豚","不思議"] },
    ],
  },
  {
    title: "アクション",
    items: [
      { kaomoji: "ヽ( ˋ(00)´ )ノ", tags: ["アクション","豚","手を上げる"] },
      { kaomoji: "(￣(oo)￣)ﾉ", tags: ["アクション","豚","挨拶"] },
      { kaomoji: "ヽ(*'(OO)')ﾉ", tags: ["アクション","豚","喜ぶ"] },
      { kaomoji: "(•(oo)•)ノ ︵ ┻━┻", tags: ["アクション","豚","ちゃぶ台"] },
      { kaomoji: "m(-（●●）-)m", tags: ["アクション","豚","お辞儀"] },
      { kaomoji: "ෆෆ(•̀🐽•̀)ෆෆ", tags: ["アクション","豚","ハート"] },
      { kaomoji: "٩(•̀🐽•́)و", tags: ["アクション","豚","ファイト"] },
      { kaomoji: "ฅ՞^🐽^՞ฅ", tags: ["アクション","豚","手"] },
      { kaomoji: "(੭՞•🐽•՞)੭", tags: ["アクション","豚","応援"] },
      { kaomoji: "(ー🐽ー)/", tags: ["アクション","豚","バイバイ"] },
      { kaomoji: "⊂⌒~⊃｡🐽｡)⊃", tags: ["アクション","豚","寝る"] },
      { kaomoji: "_(･🐽･_)⤿", tags: ["アクション","豚","隠れる"] },
      { kaomoji: ".*･ﾟᕙ[⑇ò🐽ó⑇]ᕗ.ﾟ･*.", tags: ["アクション","豚","筋肉"] },
      { kaomoji: "ᕕ( ˘ω˘ )ᕗ", tags: ["アクション","豚","歩く"] },
      { kaomoji: "ᕦ(•oo•)ᕤ", tags: ["アクション","豚","力"] },
      { kaomoji: "ʕ๑•🐽•๑ʔ", tags: ["アクション","豚","クマ風"] },
      { kaomoji: "૮⍝◜•⚇•◝⍝ა", tags: ["アクション","豚","ぷにぷに"] },
      { kaomoji: "ฅ^(˙Ꙫ˙ )^ฅ", tags: ["アクション","豚","手を出す"] },
      { kaomoji: "(ぶ゜🐽゜た)ノ", tags: ["アクション","豚","ブタ"] },
      { kaomoji: "壁]oo)￣)ジィィ", tags: ["アクション","豚","覗く"] },
    ],
  },
  {
    title: "特殊・ブヒブヒ",
    items: [
      { kaomoji: "^･🐽･^ﾌﾞﾋｰ", tags: ["特殊","豚","ブヒ"] },
      { kaomoji: "( •🐽• )ﾌﾞｰﾌﾞｰ", tags: ["特殊","豚","ブーブー"] },
      { kaomoji: "(*'(OO)'*)ﾌﾞﾋ", tags: ["特殊","豚","ブヒ"] },
      { kaomoji: "( ･´🐽･｀)ﾌﾞﾀｧ…", tags: ["特殊","豚","ブタ"] },
      { kaomoji: "(°🐽°)ﾌﾞｰﾌﾞｰ", tags: ["特殊","豚","ブーブー"] },
      { kaomoji: "( ´🐽`)y━･~~", tags: ["特殊","豚","タバコ"] },
      { kaomoji: "('⚇')ぶひぃぃ", tags: ["特殊","豚","ブヒ"] },
      { kaomoji: "｡ﾟ(ﾟ´🐽`ﾟ)ﾟ｡ぶひぃｰん｡", tags: ["特殊","豚","泣く"] },
      { kaomoji: "(๑•🐽•๑)ꔛブタ", tags: ["特殊","豚","ブタ"] },
      { kaomoji: "(๑•🐽•๑)ﾌﾞ-炊", tags: ["特殊","豚","ブー"] },
      { kaomoji: "Σ（つё（●●）ё）㌧でもない", tags: ["特殊","豚","とんでもない"] },
      { kaomoji: "!(b^○○°)", tags: ["特殊","豚","驚き"] },
      { kaomoji: "(｢🐷･ω･)｢🐷", tags: ["特殊","豚","ブヒブヒ"] },
      { kaomoji: "(🐷•᎑•🐷)", tags: ["特殊","豚","豚豚"] },
      { kaomoji: ".:° 🐖🐖╰(ˇωˇ )╯🐖🐖;｡:*", tags: ["特殊","豚","たくさん"] },
      { kaomoji: "(^🐽^)(^🐽^)(^🐽^)", tags: ["特殊","豚","三匹"] },
      { kaomoji: "🐽(•̀ω•́ )🐷", tags: ["特殊","豚","仲間"] },
      { kaomoji: "(￣(oo)￣)🎶", tags: ["特殊","豚","音楽"] },
      { kaomoji: "🐷(•́⌓•̀)", tags: ["特殊","豚","不満"] },
      { kaomoji: "🐽( ´•̥̥̥ω•̥̥̥` )ﾉ", tags: ["特殊","豚","悲しい"] },
    ],
  },
  {
    title: "装飾豚",
    items: [
      { kaomoji: "⍝◜ᐢ • 🐽 • ᐢ◝⍝", tags: ["装飾","豚","枠付き"] },
      { kaomoji: "⍝◜ᐢ•⚇•ᐢ◝⍝", tags: ["装飾","豚","四角"] },
      { kaomoji: "⍝◜ᐢ•🐽•ᐢ◝⍝", tags: ["装飾","豚","枠"] },
      { kaomoji: "⍝₍ᐢ.(00).ᐢ₎⍝", tags: ["装飾","豚","装飾"] },
      { kaomoji: "⍝₍ᐢ•(••)•ᐢ₎⍝", tags: ["装飾","豚","特殊"] },
      { kaomoji: "˚₊‧꒰ა ₍՞ σ̴̶̷̤ Ꙫ σ̴̶̷̤ ՞₎ ໒꒱ ‧₊˚", tags: ["装飾","豚","キラキラ"] },
      { kaomoji: "₍ᐢ´,,•Ꙭ•,,｀ᐢ₎", tags: ["装飾","豚","可愛い"] },
      { kaomoji: "(̂•̑₍⚇̮₎•̑)̂ ༘̏", tags: ["装飾","豚","特殊"] },
      { kaomoji: "₍˄•͈Ꙫ•͈˄₎ ༘", tags: ["装飾","豚","キラキラ"] },
      { kaomoji: "( ˙Ꙫ˙ ) ༘*", tags: ["装飾","豚","星"] },
      { kaomoji: "∪( 𓐆˘ 🐽 ˘𓐆 )∪", tags: ["装飾","豚","眠い"] },
      { kaomoji: "~ ๔(,,,･(00)･)", tags: ["装飾","豚","波"] },
      { kaomoji: "ʚ₍՞ •͈ Ꙫ •͈ ՞₎ɞ", tags: ["装飾","豚","天使"] },
      { kaomoji: "ʚ₍՞ •̀ Ꙫ •́ ՞₎ɞ", tags: ["装飾","豚","天使"] },
      { kaomoji: "(͒ ॢ ›⚇‹ ॢ)͒୭♡", tags: ["装飾","豚","ハート"] },
      { kaomoji: "۶•͈⚇•͈♡", tags: ["装飾","豚","ラブ"] },
      { kaomoji: "՞•🐽•՞", tags: ["装飾","豚","シンプル"] },
      { kaomoji: "՞ ◕ Ꙫ ◕՞", tags: ["装飾","豚","まる目"] },
      { kaomoji: "˙Ꙫ˙", tags: ["装飾","豚","ミニマル"] },
      { kaomoji: "^🐽^", tags: ["装飾","豚","シンプル"] },
    ],
  },
  {
    title: "ユニーク豚",
    items: [
      { kaomoji: "🐷´◉ω◉`", tags: ["ユニーク","豚","キラキラ目"] },
      { kaomoji: "₍ᐢ˃̵豚˂̵ᐢ₎", tags: ["ユニーク","豚","文字入り"] },
      { kaomoji: "(⁼̴́豚⁼̴̀๑)", tags: ["ユニーク","豚","ブタ文字"] },
      { kaomoji: "🐽҉ ̨҉豚҉ ̨҉🐽", tags: ["ユニーク","豚","豚文字"] },
      { kaomoji: "₍🐷₎⁾⁾豚ブヒ", tags: ["ユニーク","豚","ブヒブヒ"] },
      { kaomoji: "(´⚇豚⚇｀)", tags: ["ユニーク","豚","豚マーク"] },
      { kaomoji: "🐖ﾟﾟ･。豚･ﾟﾟ。", tags: ["ユニーク","豚","豚キラ"] },
      { kaomoji: "૮₍ ˃̵豚˂̵ ₎ა", tags: ["ユニーク","豚","豚ちゃん"] },
      { kaomoji: "༼ つ🐽豚 ༽つ", tags: ["ユニーク","豚","抱っこ"] },
      { kaomoji: "｡･:*:･ﾟ🐷豚´-", tags: ["ユニーク","豚","キラキラ豚"] },
      { kaomoji: "⌒°(❛豚❛)°⌒", tags: ["ユニーク","豚","豚まる"] },
      { kaomoji: "₍ᐢ⸝⸝› 豚 ‹⸝⸝ᐢ₎", tags: ["ユニーク","豚","豚かわ"] },
      { kaomoji: "🐽ฅ(豚•ω•豚)ฅ", tags: ["ユニーク","豚","豚豚豚"] },
      { kaomoji: "☆豚(ˊᵕˋ*)੭🐷", tags: ["ユニーク","豚","星豚"] },
      { kaomoji: "૮₍ ´• 豚 •` ₎ა", tags: ["ユニーク","豚","豚ぷく"] },
    ],
  },
  {
    title: "AA風",
    items: [
      { kaomoji: ",､＿,､ ＿,(･ω･ ) ) `u-u'-u'", tags: ["AA風","豚","連なる"] },
      { kaomoji: "ε⌒ﾍ⌒ヽﾌ ( ( ･ω･)", tags: ["AA風","豚","横向き"] },
      { kaomoji: "( ^ (●●)－)＝☆", tags: ["AA風","豚","キラキラ"] },
      { kaomoji: "(-(..)-)豚", tags: ["AA風","豚","シンプル豚"] },
      { kaomoji: "^ • ( .. ) • ^", tags: ["AA風","豚","正面"] },
      { kaomoji: "(*(oo)*)", tags: ["AA風","豚","まる"] },
      { kaomoji: "(☆(●●)☆)", tags: ["AA風","豚","星"] },
      { kaomoji: "(V −(●●)−V)", tags: ["AA風","豚","V字"] },
      { kaomoji: "<(^oo^)>", tags: ["AA風","豚","手を広げる"] },
      { kaomoji: "^(oo)^", tags: ["AA風","豚","シンプル"] },
    ],
  },
];
