import type { Metadata } from "next";
import type { KaomojiCollectionGroup, KaomojiFaqProps, KaomojiHeroProps, KaomojiWhatProps, KaomojiWhyProps } from "@/features/kaomoji/types";
import { withCanonical } from "@/lib/seo";
import { uniq } from "@/features/kaomoji/data/uniq";

export const metadata: Metadata = { title: "バレンタイン顔文字一覧（Kaomoji）｜愛を伝えるメッセージをコピペ", description: "バレンタイン顔文字をまとめて掲載。", ...withCanonical("/barentain-kaomoji") };
export const barentainKaomojiHeroContent: KaomojiHeroProps = { title: "バレンタイン顔文字一覧", kaomoji: "💝(*´▽`*)💝", subtitle: "愛を伝えるメッセージ【コピペ簡単】", description: "バレンタイン顔文字は、愛や感謝を伝える特別な表現。", primaryCta: { href: "#list", label: "顔文字を探す" }, secondaryCta: { href: "/", label: "ホームへ" } };
export const barentainKaomojiWhatContent: KaomojiWhatProps = { heading: "バレンタイン顔文字とは？", intro: "愛を伝える表現。", usageHeading: "使えるシーン", usageItems: ["バレンタインデー", "愛の告白"], typesHeading: "タイプ", types: [{ title: "ハート系", description: "愛の気持ち。", example: "例：💝Happy Valentine💝" }], featuresHeading: "特徴", features: [{ symbol: "💝", title: "ハート", description: "愛の象徴。" }] };
export const barentainKaomojiWhyContent: KaomojiWhyProps = { heading: "使い方", subheading: "愛を伝えましょう。", guideHeading: "ガイド", guides: [{ title: "告白に", bullets: ["愛の気持ち"], recommend: "おすすめ：💝Happy Valentine💝" }], cultureHeading: "文化", cultureBody: "バレンタインデーは愛を伝える特別な日。", cultureCards: [{ title: "愛の日", description: "特別な気持ちを伝える。" }], tipsHeading: "例", tips: [{ title: "バレンタイン＋メッセージ", body: "愛を込めて。", example: "例：💝Happy Valentine💝 いつもありがとう" }] };
export const barentainKaomojiFaqContent: KaomojiFaqProps = { heading: "FAQ", subheading: "バレンタイン顔文字。", items: [{ question: "コピー方法は？", answer: "コピーアイコンを押すだけ。" }] };
export const barentainKaomojiGroups: KaomojiCollectionGroup[] = [{ title: "バレンタイン", items: uniq(["💝Happy Valentine💝", "❤Valentine❤", "💖(*´▽`*)💖"]).map((kaomoji) => ({ kaomoji, tags: ["バレンタイン"] })) }];
export const barentainKaomojiPlainText: string = uniq(barentainKaomojiGroups.flatMap((group) => group.items.map((item) => item.kaomoji))).join("\n");
