import type { Metadata } from "next";
import type { KaomojiCollectionGroup, KaomojiFaqProps, KaomojiHeroProps, KaomojiWhatProps, KaomojiWhyProps } from "@/features/kaomoji/types";
import { withCanonical } from "@/lib/seo";
import { uniq } from "@/features/kaomoji/data/uniq";

export const metadata: Metadata = { title: "キャンプ顔文字一覧（Kaomoji）｜アウトドアの楽しさを表現をコピペ", description: "キャンプ顔文字をまとめて掲載。", ...withCanonical("/kyanpu-kaomoji") };
export const kyanpuKaomojiHeroContent: KaomojiHeroProps = { title: "キャンプ顔文字一覧", kaomoji: "⛺(*´▽`*)⛺", subtitle: "アウトドアの楽しさを表現【コピペ簡単】", description: "キャンプ顔文字は、アウトドアの楽しさを表現するKaomoji。", primaryCta: { href: "#list", label: "顔文字を探す" }, secondaryCta: { href: "/", label: "ホームへ" } };
export const kyanpuKaomojiWhatContent: KaomojiWhatProps = { heading: "キャンプ顔文字とは？", intro: "キャンプ顔文字は、アウトドアの楽しさを表現する表現です。", usageHeading: "使えるシーン", usageItems: ["キャンプ", "アウトドア"], typesHeading: "キャンプ顔文字のタイプ", types: [{ title: "基本", description: "シンプルで使いやすい。", example: "例：⛺(*´▽`*)⛺" }], featuresHeading: "キャンプが伝わるパーツ", features: [{ symbol: "⛺", title: "テント", description: "キャンプの象徴。" }] };
export const kyanpuKaomojiWhyContent: KaomojiWhyProps = { heading: "キャンプ顔文字を上手に使うコツ", subheading: "アウトドアの楽しさを表現。", guideHeading: "使い分けガイド", guides: [{ title: "キャンプに", bullets: ["楽しい雰囲気"], recommend: "おすすめ：⛺(*´▽`*)⛺" }], cultureHeading: "キャンプの文化", cultureBody: "キャンプは自然を楽しむアクティビティ。", cultureCards: [{ title: "自然", description: "楽しさの表現。" }], tipsHeading: "組み合わせ例", tips: [{ title: "キャンプ＋メッセージ", body: "楽しさを。", example: "例：「⛺キャンプ最高！⛺」" }] };
export const kyanpuKaomojiFaqContent: KaomojiFaqProps = { heading: "FAQ", subheading: "キャンプ顔文字。", items: [{ question: "コピー方法は？", answer: "コピーアイコンを押すだけ。" }] };
export const kyanpuKaomojiGroups: KaomojiCollectionGroup[] = [{ title: "キャンプ", items: uniq(["⛺(*´▽`*)⛺", "🏕️✨🏕️", "🔥⛺🔥"]).map((kaomoji) => ({ kaomoji, tags: ["キャンプ"] })) }];
export const kyanpuKaomojiPlainText: string = uniq(kyanpuKaomojiGroups.flatMap((group) => group.items.map((item) => item.kaomoji))).join("\n");
