import type { Metadata } from "next";

import type {
  KaomojiCollectionGroup,
  KaomojiFaqProps,
  KaomojiHeroProps,
  KaomojiWhatProps,
  KaomojiWhyProps,
} from "@/features/kaomoji/types";

import { withCanonical } from "@/lib/seo";

export const metadata: Metadata = {
  title: "アメリカ顔文字一覧（Kaomoji）｜シンプル・かわいい・ハッピーもコピペ",
  description:
    "アメリカ顔文字（Kaomoji）をまとめて掲載。シンプル・かわいい・ハッピー・笑い・ウィンク・ラブ・悲しい・驚きまで。検索＆ワンクリックでコピーして、LINE/X（Twitter）/Instagram/Discordにそのままコピペ。登録不要で無料。スマホでもOK。",
  ...withCanonical("/america-kaomoji"),
};

export const americaKaomojiHeroContent: KaomojiHeroProps = {
  title: "アメリカ顔文字一覧",
  kaomoji: "アメリカ🇺🇸  アメリカ😘",
  subtitle: "シンプル・かわいいまで【コピペ簡単】",
  description:
    "「アメリカっぽさ」が出る顔文字を集めました。シンプルから可愛い系、装飾つき、ユニーク系まで幅広く掲載。気に入った顔文字はワンクリックでコピーして、そのまま貼り付けできます。",
  primaryCta: { href: "#list", label: "顔文字を探す" },
  secondaryCta: { href: "/", label: "ホームへ" },
};

export const americaKaomojiWhatContent: KaomojiWhatProps = {
  heading: "アメリカ顔文字（Kaomoji）とは？",
  intro:
    "アメリカ顔文字は、記号や絵文字、キャラっぽいパーツを組み合わせて「アメリカ」の雰囲気を表現するKaomojiです。短い一言でもテーマが伝わりやすく、SNSやチャットのリアクションに便利です。",
  usageHeading: "使えるシーン",
  usageItems: [
    "アメリカの話題に",
    "挨拶や日常の返信に",
    "SNS投稿のテーマに",
    "かわいく盛りたいときに",
    "ネタやユニークな一言に",
  ],
  typesHeading: "アメリカ顔文字の種類",
  types: [
    {
      title: "シンプル",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: アメリカ🇺🇸  🇺🇸アメリカ",
    },
    {
      title: "かわいい",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: アメリカ😘  I❤️アメリカ",
    },
    {
      title: "ハッピー",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: アメリカ😄  アメリカ最高:D",
    },
    {
      title: "笑い",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: アメリカ😂😂😂  🤣アメリカ🤣",
    },
    {
      title: "ウィンク",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: アメリカ😉  ;)アメリカ",
    },
  ],
  featuresHeading: "アメリカらしさが出るポイント",
  features: [
    { symbol: "アメリカ🇺🇸", title: "定番", description: "まずは短くて使いやすい定番から。" },
    { symbol: "♡", title: "かわいい", description: "かわいい系のカテゴリを選ぶと柔らかい印象に。" },
    { symbol: "✨", title: "装飾", description: "絵文字や装飾つきは投稿で映えます。" },
    { symbol: "ASCII", title: "AA/アート", description: "大きめの表現はネタとして強いです。" },
  ],
};

export const americaKaomojiWhyContent: KaomojiWhyProps = {
  heading: "アメリカ顔文字の使い分け",
  subheading: "シンプルから装飾まで。場面に合わせて“雰囲気”を調整できます。",
  guideHeading: "シーン別ガイド",
  guides: [
    {
      title: "日常の返信",
      bullets: ["短めのシンプル系が自然", "文章に馴染みやすい"],
      recommend: "おすすめ: アメリカ🇺🇸",
    },
    {
      title: "SNS投稿",
      bullets: ["装飾つきでテーマが伝わりやすい", "写真と合わせると映える"],
      recommend: "おすすめ: アメリカ😘",
    },
    {
      title: "ネタ・ユニーク",
      bullets: ["ユニーク/AA系でインパクト", "使いすぎると読みにくいので注意"],
      recommend: "おすすめ: アメリカ😄",
    },
    {
      title: "かわいく盛る",
      bullets: ["可愛いカテゴリを選ぶ", "一言に添えると収まりが良い"],
      recommend: "おすすめ: アメリカ😘",
    },
  ],
  cultureHeading: "「アメリカ」モチーフは一言で伝わる",
  cultureBody:
    "アメリカは見た目のイメージが強く、短い文章でもテーマが伝わりやすいモチーフです。顔文字を添えるだけで、投稿や返信の雰囲気を軽く・かわいく・面白く調整できます。",
  cultureCards: [
    { title: "雰囲気", description: "テーマが一目で伝わる。" },
    { title: "リアクション", description: "一言に感情を足せる。" },
    { title: "盛れる", description: "装飾や絵文字で映える。" },
  ],
  tipsHeading: "すぐ使える例文",
  tips: [
    {
      title: "一言に添える",
      body: "短文 + 顔文字が使いやすいです。",
      example: "例: 今日はいい日 アメリカ🇺🇸",
    },
    {
      title: "投稿のテーマ",
      body: "写真や話題に合わせて選ぶと伝わりやすい。",
      example: "例: アメリカかわいい アメリカ😘",
    },
  ],
};

export const americaKaomojiFaqContent: KaomojiFaqProps = {
  heading: "よくある質問（FAQ）",
  subheading: "アメリカ顔文字、迷ったらここだけ見ればOK。",
  items: [
    {
      question: "アメリカ顔文字はどうやってコピーできますか？",
      answer:
        "一覧から好きな顔文字をクリックするとコピーできます。あとはLINEやSNSなどに貼り付けるだけです。",
    },
    {
      question: "文字化けしにくいのはどれ？",
      answer:
        "環境によっては絵文字や特殊文字の見え方が変わることがあります。心配なときは、記号中心のシンプル系を選ぶと安心です。",
    },
    {
      question: "タグは何のためにありますか？",
      answer:
        "検索用の目印です。気分や用途（かわいい/動作/ユニーク など）で絞り込んで探せます。",
    },
  ],
};

export const americaKaomojiGroups: KaomojiCollectionGroup[] = [
  {
    title: "シンプル",
    items: [
      { kaomoji: "アメリカ🇺🇸", tags: ["国旗","愛国","アメリカ"] },
      { kaomoji: "🇺🇸アメリカ", tags: ["国旗","シンプル","アメリカ"] },
      { kaomoji: "😃", tags: ["笑顔","元気","アメリカ"] },
      { kaomoji: ":-)", tags: ["笑顔","鼻付き","アメリカ"] },
      { kaomoji: "=)", tags: ["笑顔","シンプル"] },
      { kaomoji: ":]", tags: ["笑顔","四角口"] },
      { kaomoji: "🙂", tags: ["笑顔","やや笑顔","アメリカ"] },
      { kaomoji: ":‑)", tags: ["笑顔","基本"] },
      { kaomoji: ":(", tags: ["悲しい","シンプル","アメリカ"] },
      { kaomoji: "😢", tags: ["悲しい","涙","アメリカ"] },
      { kaomoji: "アメリカ:(", tags: ["悲しい","国名入り","アメリカ"] },
      { kaomoji: "=(", tags: ["悲しい","基本"] },
      { kaomoji: ":[", tags: ["悲しい","四角口"] },
      { kaomoji: ":‑(", tags: ["悲しい","長い鼻"] },
      { kaomoji: ":|", tags: ["無表情","真顔"] },
      { kaomoji: ":-|", tags: ["無表情","鼻付き"] },
      { kaomoji: ":/", tags: ["困惑","疑問","アメリカ"] },
      { kaomoji: ":-/", tags: ["困惑","鼻付き"] },
      { kaomoji: ":\\", tags: ["困惑","逆方向"] },
      { kaomoji: ":-\\", tags: ["困惑","鼻付き逆"] },
    ],
  },
  {
    title: "かわいい",
    items: [
      { kaomoji: "アメリカ😘", tags: ["キス","かわいい","アメリカ"] },
      { kaomoji: "I❤️アメリカ", tags: ["ラブ","愛国","アメリカ"] },
      { kaomoji: "😍", tags: ["ラブ","ハート目","アメリカ"] },
      { kaomoji: "🤗", tags: ["ハグ","かわいい","アメリカ"] },
      { kaomoji: "😇", tags: ["天使","かわいい"] },
      { kaomoji: "アメリカ🥺", tags: ["お願い","かわいい","アメリカ"] },
      { kaomoji: "アメリカ😊💕", tags: ["笑顔","ハート","国名入り","アメリカ"] },
      { kaomoji: "UwU", tags: ["かわいい","幸せ"] },
      { kaomoji: "OwO", tags: ["驚き","かわいい"] },
      { kaomoji: "😚", tags: ["キス","目閉じ"] },
      { kaomoji: "😙", tags: ["キス","笑顔"] },
      { kaomoji: "🤭", tags: ["照れ","かわいい"] },
      { kaomoji: "😌", tags: ["安心","癒し"] },
      { kaomoji: "🌟", tags: ["キラキラ","特別"] },
      { kaomoji: "✨アメリカ✨", tags: ["キラキラ","国名","アメリカ"] },
      { kaomoji: "💕", tags: ["ハート","ラブ"] },
      { kaomoji: "💗", tags: ["ハート","かわいい"] },
      { kaomoji: "💖", tags: ["ハート","キラキラ"] },
      { kaomoji: "💓", tags: ["ハート","ドキドキ"] },
      { kaomoji: "💝", tags: ["ハート","プレゼント"] },
    ],
  },
  {
    title: "ハッピー",
    items: [
      { kaomoji: "アメリカ😄", tags: ["大笑い","ハッピー","アメリカ"] },
      { kaomoji: "アメリカ最高:D", tags: ["大笑い","最高","アメリカ"] },
      { kaomoji: "😁", tags: ["笑顔","歯見せ","アメリカ"] },
      { kaomoji: ":-D", tags: ["大笑い","鼻付き"] },
      { kaomoji: "=D", tags: ["大笑い","基本"] },
      { kaomoji: ":‑D", tags: ["大笑い","長い鼻"] },
      { kaomoji: "😆", tags: ["大笑い","目閉じ"] },
      { kaomoji: "アメリカXD", tags: ["爆笑","目X","アメリカ"] },
      { kaomoji: "X‑D", tags: ["爆笑","鼻付き"] },
      { kaomoji: "😂", tags: ["爆笑","涙","アメリカ"] },
      { kaomoji: "🤣", tags: ["爆笑","転げる"] },
      { kaomoji: "xD", tags: ["笑い","小文字"] },
      { kaomoji: "x‑D", tags: ["笑い","小文字鼻"] },
      { kaomoji: "😀", tags: ["笑顔","シンプル"] },
      { kaomoji: "8D", tags: ["大笑い","メガネ"] },
      { kaomoji: "8‑D", tags: ["大笑い","メガネ鼻"] },
      { kaomoji: "BD", tags: ["大笑い","サングラス"] },
      { kaomoji: "😸", tags: ["猫笑顔","動物"] },
      { kaomoji: ":>", tags: ["笑顔","変形"] },
      { kaomoji: ":3", tags: ["猫口","かわいい"] },
    ],
  },
  {
    title: "笑い",
    items: [
      { kaomoji: "アメリカ😂😂😂", tags: ["爆笑","連続","アメリカ"] },
      { kaomoji: "🤣アメリカ🤣", tags: ["爆笑","転げる","アメリカ"] },
      { kaomoji: "XDDD", tags: ["超笑い","強調"] },
      { kaomoji: ":DDD", tags: ["超笑い","口大"] },
      { kaomoji: "😹", tags: ["猫笑い","涙"] },
      { kaomoji: "X)", tags: ["笑い","目X"] },
      { kaomoji: "X‑)", tags: ["笑い","鼻付き"] },
      { kaomoji: "xDD", tags: ["大笑い","強調"] },
      { kaomoji: ":)))", tags: ["超笑顔","三重口"] },
      { kaomoji: "=)))", tags: ["超笑顔","三重"] },
      { kaomoji: ":]]]", tags: ["超笑顔","四角"] },
      { kaomoji: "😄😄", tags: ["笑顔","連続"] },
      { kaomoji: "c:", tags: ["笑顔","変形"] },
      { kaomoji: "C:", tags: ["笑顔","大文字"] },
      { kaomoji: ":o)", tags: ["笑顔","丸鼻"] },
      { kaomoji: "[:", tags: ["笑顔","逆四角"] },
      { kaomoji: "=]", tags: ["笑顔","四角口"] },
      { kaomoji: "8)", tags: ["笑顔","メガネ"] },
      { kaomoji: "8‑)", tags: ["笑顔","メガネ鼻"] },
      { kaomoji: "B)", tags: ["笑顔","サングラス"] },
    ],
  },
  {
    title: "ウィンク",
    items: [
      { kaomoji: "アメリカ😉", tags: ["ウィンク","かわいい","アメリカ"] },
      { kaomoji: ";)アメリカ", tags: ["ウィンク","シンプル","アメリカ"] },
      { kaomoji: ";‑)", tags: ["ウィンク","鼻付き"] },
      { kaomoji: ";D", tags: ["ウィンク","大笑い"] },
      { kaomoji: ";‑D", tags: ["ウィンク","大笑い鼻"] },
      { kaomoji: ";]", tags: ["ウィンク","四角"] },
      { kaomoji: ";‑]", tags: ["ウィンク","四角鼻"] },
      { kaomoji: "アメリカ😜", tags: ["ウィンク","舌出し","アメリカ"] },
      { kaomoji: "😝", tags: ["ウィンク","べー"] },
      { kaomoji: ";P", tags: ["ウィンク","舌"] },
      { kaomoji: ";‑P", tags: ["ウィンク","舌鼻"] },
      { kaomoji: ";p", tags: ["ウィンク","小舌"] },
      { kaomoji: ";‑p", tags: ["ウィンク","小舌鼻"] },
      { kaomoji: ";^)", tags: ["ウィンク","変形"] },
      { kaomoji: ";3", tags: ["ウィンク","猫口"] },
      { kaomoji: "😏", tags: ["ニヤリ","いたずら"] },
      { kaomoji: ";>", tags: ["ウィンク","変形口"] },
      { kaomoji: ";o)", tags: ["ウィンク","丸鼻"] },
      { kaomoji: ";*", tags: ["ウィンク","キス"] },
      { kaomoji: ";‑*", tags: ["ウィンク","キス鼻"] },
    ],
  },
  {
    title: "ラブ",
    items: [
      { kaomoji: "❤️アメリカ❤️", tags: ["ハート","ラブ","アメリカ"] },
      { kaomoji: "アメリカ<3", tags: ["ハート","シンプル","アメリカ"] },
      { kaomoji: "💖アメリカ💖", tags: ["ハート","キラキラ","アメリカ"] },
      { kaomoji: ":*", tags: ["キス","シンプル"] },
      { kaomoji: ":-*", tags: ["キス","鼻付き"] },
      { kaomoji: ":‑*", tags: ["キス","長鼻"] },
      { kaomoji: ":^*", tags: ["キス","変形"] },
      { kaomoji: "💋", tags: ["キス","唇"] },
      { kaomoji: "😗", tags: ["キス","顔"] },
      { kaomoji: "<<3", tags: ["ハート","強調"] },
      { kaomoji: "<<<3", tags: ["ハート","超強調"] },
      { kaomoji: "</3", tags: ["失恋","ハート"] },
      { kaomoji: "💔", tags: ["失恋","割れ"] },
      { kaomoji: "😻", tags: ["猫ハート","ラブ"] },
      { kaomoji: "😽", tags: ["猫キス","ラブ"] },
      { kaomoji: "xoxo", tags: ["ハグキス","ラブ"] },
      { kaomoji: "XOXO", tags: ["ハグキス","大文字"] },
      { kaomoji: "💞", tags: ["ハート","回転"] },
      { kaomoji: "💕💕", tags: ["ハート","連続"] },
      { kaomoji: "❤️‍🔥", tags: ["ハート","炎"] },
    ],
  },
  {
    title: "悲しい",
    items: [
      { kaomoji: "😭", tags: ["大泣き","悲しい","アメリカ"] },
      { kaomoji: ":'(", tags: ["泣く","涙","アメリカ"] },
      { kaomoji: ":‑'(", tags: ["泣く","鼻付き"] },
      { kaomoji: "😿", tags: ["猫泣く","悲しい"] },
      { kaomoji: ":'‑(", tags: ["泣く","長鼻"] },
      { kaomoji: ";(", tags: ["泣く","片目"] },
      { kaomoji: ";‑(", tags: ["泣く","片目鼻"] },
      { kaomoji: "T_T", tags: ["大泣き","涙川"] },
      { kaomoji: "T.T", tags: ["大泣き","点涙"] },
      { kaomoji: "😔", tags: ["落ち込む","悲しい"] },
      { kaomoji: "😞", tags: ["失望","悲しい"] },
      { kaomoji: "😥", tags: ["悲しい","汗"] },
      { kaomoji: "QQ", tags: ["泣く","目"] },
      { kaomoji: "Q_Q", tags: ["泣く","涙"] },
      { kaomoji: "ToT", tags: ["大泣き","小文字"] },
      { kaomoji: ";_;", tags: ["泣く","シンプル"] },
      { kaomoji: "😪", tags: ["眠い","悲しい"] },
      { kaomoji: "😓", tags: ["冷や汗","困る"] },
      { kaomoji: ">:(", tags: ["不機嫌","悲しい"] },
      { kaomoji: "D:", tags: ["ショック","悲しい"] },
    ],
  },
  {
    title: "驚き",
    items: [
      { kaomoji: "😮", tags: ["驚き","口開け","アメリカ"] },
      { kaomoji: ":O", tags: ["驚き","シンプル","アメリカ"] },
      { kaomoji: "😲", tags: ["驚き","ビックリ"] },
      { kaomoji: ":-O", tags: ["驚き","鼻付き"] },
      { kaomoji: ":‑O", tags: ["驚き","長鼻"] },
      { kaomoji: ":o", tags: ["驚き","小口"] },
      { kaomoji: ":-o", tags: ["驚き","小口鼻"] },
      { kaomoji: "😯", tags: ["驚き","静か"] },
      { kaomoji: "😦", tags: ["驚き","口開け"] },
      { kaomoji: "😧", tags: ["驚き","不安"] },
      { kaomoji: "8O", tags: ["驚き","メガネ"] },
      { kaomoji: "8‑O", tags: ["驚き","メガネ鼻"] },
      { kaomoji: "O_O", tags: ["驚き","大目"] },
      { kaomoji: "O.O", tags: ["驚き","点目"] },
      { kaomoji: "o_o", tags: ["驚き","小目"] },
      { kaomoji: "o.o", tags: ["驚き","小点目"] },
      { kaomoji: "😳", tags: ["驚き","赤面"] },
      { kaomoji: ":0", tags: ["驚き","ゼロ口"] },
      { kaomoji: "D8", tags: ["驚き","ショック"] },
      { kaomoji: "DX", tags: ["驚き","X目"] },
    ],
  },
  {
    title: "怒り",
    items: [
      { kaomoji: "😠", tags: ["怒り","不機嫌","アメリカ"] },
      { kaomoji: "😡", tags: ["怒り","激怒","アメリカ"] },
      { kaomoji: ">:‑(", tags: ["怒り","眉鼻"] },
      { kaomoji: ">:[", tags: ["怒り","四角"] },
      { kaomoji: "😤", tags: ["怒り","鼻息"] },
      { kaomoji: ">:O", tags: ["怒り","大声"] },
      { kaomoji: ">:‑O", tags: ["怒り","大声鼻"] },
      { kaomoji: ">:|", tags: ["怒り","無表情"] },
      { kaomoji: "😾", tags: ["猫怒り","不機嫌"] },
      { kaomoji: ">:/", tags: ["怒り","困惑"] },
      { kaomoji: ">:\\", tags: ["怒り","逆困惑"] },
      { kaomoji: "D:<", tags: ["怒り","逆向き"] },
      { kaomoji: "D:<<", tags: ["怒り","強調"] },
      { kaomoji: "😒", tags: ["不機嫌","冷たい"] },
      { kaomoji: "🙄", tags: ["呆れ","目回し"] },
      { kaomoji: "😑", tags: ["無表情","怒り"] },
      { kaomoji: ">:D", tags: ["悪い笑い","いたずら"] },
      { kaomoji: "😈", tags: ["悪魔","いたずら"] },
      { kaomoji: ">:)", tags: ["悪い笑顔","意地悪"] },
    ],
  },
  {
    title: "特別",
    items: [
      { kaomoji: "アメリカ😎", tags: ["クール","サングラス","アメリカ"] },
      { kaomoji: "アメリカ🎉", tags: ["パーティ","祝い","アメリカ"] },
      { kaomoji: "8-)", tags: ["メガネ","笑顔"] },
      { kaomoji: "😴", tags: ["寝る","眠い"] },
      { kaomoji: ":‑o", tags: ["あくび","眠い"] },
      { kaomoji: "😴💤", tags: ["寝る","zzz","アメリカ"] },
      { kaomoji: "😛", tags: ["舌出し","遊び","アメリカ"] },
      { kaomoji: ":P", tags: ["舌出し","シンプル","アメリカ"] },
      { kaomoji: ":-P", tags: ["舌出し","鼻付き"] },
      { kaomoji: ":p", tags: ["舌出し","小文字"] },
      { kaomoji: ":-p", tags: ["舌出し","小鼻"] },
      { kaomoji: "xP", tags: ["舌出し","目X"] },
      { kaomoji: "xp", tags: ["舌出し","x目"] },
      { kaomoji: "🤓", tags: ["オタク","メガネ"] },
      { kaomoji: "🥳アメリカ🥳", tags: ["パーティ","祝い","アメリカ"] },
      { kaomoji: "🎉", tags: ["祝い","パーティ"] },
      { kaomoji: "🎊", tags: ["祝い","くす玉"] },
      { kaomoji: "🌈", tags: ["虹","希望"] },
      { kaomoji: "⭐", tags: ["星","特別"] },
      { kaomoji: "✌️アメリカ✌️", tags: ["ピース","平和","アメリカ"] },
    ],
  },
];

