import type { Metadata } from "next";

import type {
  KaomojiCollectionGroup,
  KaomojiFaqProps,
  KaomojiHeroProps,
  KaomojiWhatProps,
  KaomojiWhyProps,
} from "@/features/kaomoji/types";

import { withCanonical } from "@/lib/seo";

export const metadata: Metadata = {
  title: "カエル顔文字一覧（Kaomoji）｜ASCII Art・基本的なカエル・可愛い系もコピペ",
  description:
    "カエル顔文字（Kaomoji）をまとめて掲載。ASCII Art・基本的なカエル・可愛い系・絵文字入り・アクション系・特殊表現まで。検索＆ワンクリックでコピーして、LINE/X（Twitter）/Instagram/Discordにそのままコピペ。登録不要で無料。スマホでもOK。",
  ...withCanonical("/kaeru-kaomoji"),
};

export const kaeruKaomojiHeroContent: KaomojiHeroProps = {
  title: "カエル顔文字一覧",
  kaomoji: "Θ_Θ  ₍𝄐𓂅𝄐₎",
  subtitle: "ASCII Art・基本的なカエルまで【コピペ簡単】",
  description:
    "「カエルっぽさ」が出る顔文字を集めました。シンプルから可愛い系、装飾つき、ユニーク系まで幅広く掲載。気に入った顔文字はワンクリックでコピーして、そのまま貼り付けできます。",
  primaryCta: { href: "#list", label: "顔文字を探す" },
  secondaryCta: { href: "/", label: "ホームへ" },
};

export const kaeruKaomojiWhatContent: KaomojiWhatProps = {
  heading: "カエル顔文字（Kaomoji）とは？",
  intro:
    "カエル顔文字は、記号や絵文字、キャラっぽいパーツを組み合わせて「カエル」の雰囲気を表現するKaomojiです。短い一言でもテーマが伝わりやすく、SNSやチャットのリアクションに便利です。",
  usageHeading: "使えるシーン",
  usageItems: [
    "カエルの話題に",
    "挨拶や日常の返信に",
    "SNS投稿のテーマに",
    "かわいく盛りたいときに",
    "ネタやユニークな一言に",
  ],
  typesHeading: "カエル顔文字の種類",
  types: [
    {
      title: "ASCII Art",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ⠀(●)(●) （ ϖ ）=3 ⠀/ ⌒ヽ （人＿__つ_つ  ⠀ ◒_◒ ( ๑ • ๑ )",
    },
    {
      title: "基本的なカエル",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: Θ_Θ  (Θ-Θ)",
    },
    {
      title: "可愛い系",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ₍𝄐𓂅𝄐₎  ₍𝄐◡𝄐₎",
    },
    {
      title: "絵文字入り",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: 🐸( '-' 🐸 )ｶｴﾙﾊﾟﾝﾁ  🐸( '-' 🐸 )ｹﾞｺｹﾞｺ ｲﾏｶﾗ ｶｴﾙ",
    },
    {
      title: "アクション系",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ｶｴﾘﾏｽ♡ｽﾀｽﾀ(((((*´･ω･)  (・∀・)ｶｴﾙ!!",
    },
  ],
  featuresHeading: "カエルらしさが出るポイント",
  features: [
    { symbol: "Θ_Θ", title: "定番", description: "まずは短くて使いやすい定番から。" },
    { symbol: "♡", title: "かわいい", description: "かわいい系のカテゴリを選ぶと柔らかい印象に。" },
    { symbol: "✨", title: "装飾", description: "絵文字や装飾つきは投稿で映えます。" },
    { symbol: "ASCII", title: "AA/アート", description: "大きめの表現はネタとして強いです。" },
  ],
};

export const kaeruKaomojiWhyContent: KaomojiWhyProps = {
  heading: "カエル顔文字の使い分け",
  subheading: "シンプルから装飾まで。場面に合わせて“雰囲気”を調整できます。",
  guideHeading: "シーン別ガイド",
  guides: [
    {
      title: "日常の返信",
      bullets: ["短めのシンプル系が自然", "文章に馴染みやすい"],
      recommend: "おすすめ: Θ_Θ",
    },
    {
      title: "SNS投稿",
      bullets: ["装飾つきでテーマが伝わりやすい", "写真と合わせると映える"],
      recommend: "おすすめ: ₍𝄐𓂅𝄐₎",
    },
    {
      title: "ネタ・ユニーク",
      bullets: ["ユニーク/AA系でインパクト", "使いすぎると読みにくいので注意"],
      recommend: "おすすめ: ⠀(●)(●) （ ϖ ）=3 ⠀/ ⌒ヽ （人＿__つ_つ",
    },
    {
      title: "かわいく盛る",
      bullets: ["可愛いカテゴリを選ぶ", "一言に添えると収まりが良い"],
      recommend: "おすすめ: ₍𝄐𓂅𝄐₎",
    },
  ],
  cultureHeading: "「カエル」モチーフは一言で伝わる",
  cultureBody:
    "カエルは見た目のイメージが強く、短い文章でもテーマが伝わりやすいモチーフです。顔文字を添えるだけで、投稿や返信の雰囲気を軽く・かわいく・面白く調整できます。",
  cultureCards: [
    { title: "雰囲気", description: "テーマが一目で伝わる。" },
    { title: "リアクション", description: "一言に感情を足せる。" },
    { title: "盛れる", description: "装飾や絵文字で映える。" },
  ],
  tipsHeading: "すぐ使える例文",
  tips: [
    {
      title: "一言に添える",
      body: "短文 + 顔文字が使いやすいです。",
      example: "例: 今日はいい日 Θ_Θ",
    },
    {
      title: "投稿のテーマ",
      body: "写真や話題に合わせて選ぶと伝わりやすい。",
      example: "例: カエルかわいい ₍𝄐𓂅𝄐₎",
    },
  ],
};

export const kaeruKaomojiFaqContent: KaomojiFaqProps = {
  heading: "よくある質問（FAQ）",
  subheading: "カエル顔文字、迷ったらここだけ見ればOK。",
  items: [
    {
      question: "カエル顔文字はどうやってコピーできますか？",
      answer:
        "一覧から好きな顔文字をクリックするとコピーできます。あとはLINEやSNSなどに貼り付けるだけです。",
    },
    {
      question: "文字化けしにくいのはどれ？",
      answer:
        "環境によっては絵文字や特殊文字の見え方が変わることがあります。心配なときは、記号中心のシンプル系を選ぶと安心です。",
    },
    {
      question: "タグは何のためにありますか？",
      answer:
        "検索用の目印です。気分や用途（かわいい/動作/ユニーク など）で絞り込んで探せます。",
    },
  ],
};

export const kaeruKaomojiGroups: KaomojiCollectionGroup[] = [
  {
    title: "ASCII Art",
    items: [
      { kaomoji: "⠀(●)(●)\n（ ϖ ）=3\n⠀/ ⌒ヽ\n（人＿__つ_つ", tags: ["ASCII","人気","大きい"] },
      { kaomoji: "⠀ ◒_◒\n( ๑ • ๑ )", tags: ["ASCII","可愛い"] },
      { kaomoji: "⠀(●)(●)ヽ\n⠀(＿ ϖ ＿＿）\n⠀((・ϖ・`),,)\n⠀⠀c_uu_c__)", tags: ["ASCII","大きい"] },
      { kaomoji: "⠀⠀⠀_ _\n⠀⠀(o)–(o)\n⠀/.______.\\\n⠀\\________/\n⠀⠀./ \\.\n⠀⠀( . , )\n⠀⠀\\ \\_\\\\\n⠀⠀~~ ~~ ~~", tags: ["ASCII","大きい","詳細"] },
      { kaomoji: "⠀⠀⠀⠀,,-◉ー、\n⠀／ ／ ／￣\n( ⌒)__｡〈_｡\n⠀￣¯¯° ￣°", tags: ["ASCII","可愛い"] },
      { kaomoji: "／￣＼／￣＼\n｜ ●｜● ｜\n>――＾ー―<\n( 〇 〇 )\n＼＿＼／＿／", tags: ["ASCII","大きい"] },
      { kaomoji: "✧\n⠀( ●)(● )\n⠀(◯⌵◯)\nΣ/⋆. ⑅˚₊\\フ\n⠀⠀⌵ ⌵", tags: ["ASCII","星","可愛い"] },
      { kaomoji: "⠀⠀⠀⠀＿_ _＿\n⠀⠀⠀⠀((･)Ｖ(･))\n⠀⠀⠀⠀/'＿‥＿ﾉ\n⠀＿／⠀⠀⠀⠀⠀＼＿\n⠀≧／ ￣￣/'＼≦\n⠀⠀.(⌒＼ ノ⌒)\n⠀⠀⠀＞.<￣>.＜\n⠀⠀⠀￣￣ ￣￣", tags: ["ASCII","大きい","詳細"] },
      { kaomoji: "┈┈┈┈╱▔╲╮╭╱▔╲┈┈┈┈\n┈┈┈┈▏▉▕╰╯▏▉▕┈┈┈┈\n┈┈┈╱╲▂╱┈┈╲▂╱╲┈┈┈\n┈╱▔┈┈┈┈┈┈┈┈┈┈▔╲┈\n┈╲╲▂▂▂▂▂▂▂▂▂▂╱╱┈\n┈╱╲┈┈┈┈┈┈┈┈┈┈╱╲┈\n╱┈╱▏▕▔╲▃╱▔▏┈▕╲┈╲\n▏▕┈▏▕▂╱▔╲▂▏┈▕┈▏▕", tags: ["ASCII","大きい","装飾"] },
      { kaomoji: "(●)(●)ヽ\n(＿ー＿＿）\nc_uu_c__)", tags: ["ASCII","シンプル"] },
    ],
  },
  {
    title: "基本的なカエル",
    items: [
      { kaomoji: "Θ_Θ", tags: ["基本","人気","シンプル"] },
      { kaomoji: "(Θ-Θ)", tags: ["基本","普通"] },
      { kaomoji: "(Θ‥Θ)", tags: ["基本","可愛い"] },
      { kaomoji: "(ΘωΘ)", tags: ["基本","笑顔"] },
      { kaomoji: "(oΘωΘo)", tags: ["基本","可愛い"] },
      { kaomoji: "|ΘωΘ)ﾉ", tags: ["基本","挨拶"] },
      { kaomoji: "(ΘнΘ)", tags: ["基本","普通"] },
      { kaomoji: "ΘωΘ", tags: ["基本","シンプル"] },
      { kaomoji: "( Θ‥Θ)", tags: ["基本","可愛い"] },
      { kaomoji: "(Θ‥Θ )ｹﾛｹﾛ", tags: ["基本","鳴き声"] },
      { kaomoji: "(Θ‥Θ)ｹﾞｺｹﾞｺ", tags: ["基本","鳴き声"] },
      { kaomoji: "₍𝄐⩌𝄐₎", tags: ["基本","可愛い","人気"] },
      { kaomoji: "₍𝄐⁀̲𝄐₎", tags: ["基本","可愛い"] },
      { kaomoji: "₍𝄐 ̫𝄐₎", tags: ["基本","可愛い"] },
      { kaomoji: "₍ᤱᴼ̓ˬᴼ̓ᤱ₎", tags: ["基本","可愛い"] },
      { kaomoji: "m₍⁽ॱ⁾᷼⁽ॱ⁾₎m", tags: ["基本","手"] },
      { kaomoji: "(ӧ)(Ӧ)(ӧ)～♬", tags: ["基本","音楽"] },
      { kaomoji: "₍⁽ॱ⁾᷼⁽ॱ⁾₎", tags: ["基本","シンプル"] },
      { kaomoji: "₍ᐢ_ᐢ₎", tags: ["基本","シンプル"] },
      { kaomoji: "(๑⁰ 〰⁰)ｹﾛｰﾝ", tags: ["基本","鳴き声"] },
      { kaomoji: "<(`ΘωΘ´)>", tags: ["基本","元気"] },
      { kaomoji: "₍⁽ॱ⁾⁽ॱ⁾₎", tags: ["基本","シンプル"] },
      { kaomoji: "₍⸝⸝⁽´⁾₋⁽`⁾⸝⸝₎", tags: ["基本","可愛い"] },
      { kaomoji: "w( ⊙◇⊙)w", tags: ["基本","驚き"] },
      { kaomoji: "₍𝄐 ̫͡ 𝄐₎", tags: ["基本","可愛い"] },
      { kaomoji: "₍៰ᴼ́ ᪶ᴼ̀៰₎", tags: ["基本","特別"] },
      { kaomoji: "(°／＼°)ゲコ", tags: ["基本","鳴き声"] },
      { kaomoji: "(Θ︹Θ)", tags: ["基本","悲しい"] },
      { kaomoji: "පූ", tags: ["基本","シンプル"] },
      { kaomoji: "⋅⃘⋅⃘͜", tags: ["基本","シンプル"] },
      { kaomoji: "(-)_(-)  ", tags: ["基本","眠い"] },
      { kaomoji: "(ΘoΘ)ﾉｼ", tags: ["基本","挨拶"] },
      { kaomoji: "（・‥・）ｹﾞｺｹﾞｺ", tags: ["基本","鳴き声"] },
      { kaomoji: "( ・ ∀ ・)", tags: ["基本","笑顔"] },
      { kaomoji: "n('～')n", tags: ["基本","手"] },
      { kaomoji: "≡( ' ' )", tags: ["基本","シンプル"] },
      { kaomoji: "@'^'@", tags: ["基本","可愛い"] },
      { kaomoji: "ｗ<' ◇ '>ｗ", tags: ["基本","手"] },
    ],
  },
  {
    title: "可愛い系",
    items: [
      { kaomoji: "₍𝄐𓂅𝄐₎", tags: ["可愛い","人気"] },
      { kaomoji: "₍𝄐◡𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐▿𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐ꈊ𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐ー𝄐₎", tags: ["可愛い","普通"] },
      { kaomoji: "₍𝄐𓃰𝄐₎", tags: ["可愛い","特別"] },
      { kaomoji: "₍𝄐⌵𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐‿𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐𝆬𝄐₎", tags: ["可愛い","特別"] },
      { kaomoji: "₍𝄐꒳𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "<₍𝄐◡𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐▿𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐ꈊ𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐ー𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐⌵𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐‿𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐꒳𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐𓂅𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐𝆬𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "<₍𝄐𓃰𝄐₎>", tags: ["可愛い","手"] },
      { kaomoji: "(Θ◡Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(Θ▿Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(ΘꈊΘ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(ΘーΘ)", tags: ["可愛い","普通"] },
      { kaomoji: "(Θ⌵Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(Θ‿Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(Θ꒳Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(ΘvΘ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(Θ∀Θ)", tags: ["可愛い","笑顔"] },
      { kaomoji: "(Θ⊥Θ)", tags: ["可愛い","シンプル"] },
      { kaomoji: "₍𝄐∀𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐v𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐⊥𝄐₎", tags: ["可愛い","シンプル"] },
      { kaomoji: "₍𝄐ಎ𝄐₎", tags: ["可愛い","笑顔"] },
      { kaomoji: "₍𝄐ᴗ𝄐₎", tags: ["可愛い","笑顔"] },
    ],
  },
  {
    title: "絵文字入り",
    items: [
      { kaomoji: "🐸( '-' 🐸 )ｶｴﾙﾊﾟﾝﾁ", tags: ["絵文字","人気","パンチ"] },
      { kaomoji: "🐸( '-' 🐸 )ｹﾞｺｹﾞｺ ｲﾏｶﾗ ｶｴﾙ", tags: ["絵文字","帰る"] },
      { kaomoji: "ｶｴﾙｩ(｢🐸･ω･)｢🐸", tags: ["絵文字","帰る"] },
      { kaomoji: "🐸( '-' 🐸 )ｹﾞｺｹﾞｺ ｶｴﾙ", tags: ["絵文字","帰る"] },
      { kaomoji: "(っ∵)╮ =͟͟͞͞ 🐸", tags: ["絵文字","投げる"] },
      { kaomoji: "帰る！(っ∵)╮ =͟͟͞͞ 🐸", tags: ["絵文字","帰る"] },
      { kaomoji: "🐸( '-' 🐸 )ｶｴﾙｯﾁｬﾝ", tags: ["絵文字","可愛い"] },
      { kaomoji: "🐸(ﾟдﾟ)ノｶｴﾙﾖ！", tags: ["絵文字","帰る"] },
      { kaomoji: "(´･ω･`)🐸", tags: ["絵文字","可愛い"] },
      { kaomoji: "🐸＼(ﾟдﾟ)／ｽﾞﾄﾞｰﾝ", tags: ["絵文字","登場"] },
      { kaomoji: "(Θ⌂Θ)つヽ🐸ノ", tags: ["絵文字","持つ"] },
      { kaomoji: "🐸(⊃｡•́‿•̀｡)⊃", tags: ["絵文字","可愛い"] },
      { kaomoji: "( ˘ω˘ )🐸", tags: ["絵文字","可愛い"] },
      { kaomoji: "🐸🎶(ΘゝΘ)ﾉ", tags: ["絵文字","音楽"] },
      { kaomoji: "(⊃˘ω˘)⊃🐸", tags: ["絵文字","持つ"] },
      { kaomoji: "🐸(≖ω≖)", tags: ["絵文字","可愛い"] },
      { kaomoji: "🐸(⦁•̀ω•́⦁)", tags: ["絵文字","可愛い"] },
      { kaomoji: "(Θ͜θ)ゞ🦋", tags: ["絵文字","蝶"] },
      { kaomoji: "( ・ω・)🐸", tags: ["絵文字","可愛い"] },
      { kaomoji: "🐸(´•̥̥̥ω•̥̥̥`🐸)", tags: ["絵文字","泣く"] },
      { kaomoji: "(｡•́︿•̀｡)🦋🐸", tags: ["絵文字","悲しい"] },
      { kaomoji: "ヽ(°▽°)ﾉ🐸", tags: ["絵文字","元気"] },
      { kaomoji: "🐸ε=ε=ε=(ง ´˘` )ง", tags: ["絵文字","走る"] },
      { kaomoji: "( ｀・ω・)⊃🐸", tags: ["絵文字","持つ"] },
      { kaomoji: "(・ω・)🐸ノシ", tags: ["絵文字","挨拶"] },
    ],
  },
  {
    title: "アクション系",
    items: [
      { kaomoji: "ｶｴﾘﾏｽ♡ｽﾀｽﾀ(((((*´･ω･)", tags: ["アクション","人気","帰る"] },
      { kaomoji: "(・∀・)ｶｴﾙ!!", tags: ["アクション","帰る"] },
      { kaomoji: "ε=(ﾉ‥)ﾉ", tags: ["アクション","帰る"] },
      { kaomoji: "ｲﾏｶﾗ(*・∀・)ｶｴﾙ🐸", tags: ["アクション","帰る"] },
      { kaomoji: "┌(Θ_Θ ┐)┐ｹﾛｯ", tags: ["アクション","鳴き声"] },
      { kaomoji: "ε＝┏(･ω･)┛", tags: ["アクション","帰る"] },
      { kaomoji: "ｹﾛ(Θ‥Θ )( Θ‥Θ)ｹﾛ", tags: ["アクション","鳴き声"] },
      { kaomoji: "ｺﾚｵﾏｴ( ･‪⌓･)☞𓆏", tags: ["アクション","指差し"] },
      { kaomoji: "┌(┌oΘωΘo)┐ｹﾞｺｫ", tags: ["アクション","鳴き声"] },
      { kaomoji: "(*・∀・)ｶｴﾙ !", tags: ["アクション","帰る"] },
      { kaomoji: "ｶｴﾙ(ง˘³˘)วｶｴﾙ", tags: ["アクション","帰る"] },
      { kaomoji: "ε=(ﾉ‥)ﾉｶｴﾙﾏｽ", tags: ["アクション","帰る"] },
      { kaomoji: "ｶｴﾘﾏｽｩ…(^_^)/~~ﾊﾞｲﾊﾞｲ🏡🚲．．💨💨", tags: ["アクション","帰る","長い"] },
      { kaomoji: "∧θДθ∧ｶｴﾙﾈ", tags: ["アクション","帰る"] },
      { kaomoji: "🍋 ✨🚪(-'ﾛ'- )⊃_(´ㅅ`_)_ ))ｽﾞﾄﾞｰﾝ", tags: ["アクション","特別"] },
      { kaomoji: "ｲｿｲﾃﾞｶｴﾙ!ε≡≡ﾍ( ´Д`)ﾉ", tags: ["アクション","帰る","急ぐ"] },
      { kaomoji: "今から帰ります｡･*･:≡( ε:)", tags: ["アクション","帰る"] },
      { kaomoji: "｡･*･:≡( ε:)🏠", tags: ["アクション","帰る"] },
      { kaomoji: "(*・∀・)ｶｴﾚ！", tags: ["アクション","帰る"] },
      { kaomoji: "εε＝(((((ﾉ･ω･)ﾉﾑｽﾒ ｶｴﾙｰ", tags: ["アクション","帰る"] },
      { kaomoji: "さらばじゃ！ε＝┏(･ω･)┛", tags: ["アクション","帰る"] },
      { kaomoji: "(・∀・)カエル!!", tags: ["アクション","帰る"] },
      { kaomoji: "( ˘•ω•˘)ｶｴﾙ", tags: ["アクション","帰る"] },
      { kaomoji: "🐸( ˘•ω•˘)ｹﾞｺ", tags: ["アクション","鳴き声"] },
      { kaomoji: "ﾍ(ﾟ∀ﾟ)ﾉｶｴﾙｰ", tags: ["アクション","帰る"] },
      { kaomoji: "(Θ_Θ)Σ(｀･ω･´)ﾉｼ", tags: ["アクション","挨拶"] },
      { kaomoji: "┏(＾ω＾)┛カエル", tags: ["アクション","帰る"] },
      { kaomoji: "(・ω・)ノｼ カエル", tags: ["アクション","帰る"] },
      { kaomoji: "ヾ(｡･ω･｡)ｶｴﾙ!", tags: ["アクション","帰る"] },
      { kaomoji: "ヽ( ・∀・)ﾉｶｴﾙ", tags: ["アクション","帰る"] },
    ],
  },
  {
    title: "特殊表現",
    items: [
      { kaomoji: "₍𝄐 ͜͡ ₍𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐ਊ𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𐚯𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𝈗𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𐃹𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𓂃𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𐃔𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𒉼𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐𒄭𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐灬𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "<₍𝄐⩌𝄐₎>", tags: ["特殊","手"] },
      { kaomoji: "<₍𝄐 ̫͡ 𝄐₎>", tags: ["特殊","手"] },
      { kaomoji: "<₍𝄐⁀̲𝄐₎>", tags: ["特殊","手"] },
      { kaomoji: "₍𝄐∩𝄐₎", tags: ["特殊","可愛い"] },
      { kaomoji: "₍𝄐๏𝄐₎", tags: ["特殊","驚き"] },
      { kaomoji: "₍𝄐◠𝄐₎", tags: ["特殊","笑顔"] },
      { kaomoji: "<₍𝄐๏𝄐₎>", tags: ["特殊","驚き","手"] },
      { kaomoji: "<₍𝄐◠𝄐₎>", tags: ["特殊","笑顔","手"] },
      { kaomoji: "๑ ๑ ( ‪ ·͜· ) ( ∪ ∪ )", tags: ["特殊","可愛い"] },
      { kaomoji: "◉ ◉ ( ‪ ·͜· )", tags: ["特殊","可愛い"] },
    ],
  },
];

