import type { Metadata } from "next";

import type {
  KaomojiCollectionGroup,
  KaomojiFaqProps,
  KaomojiHeroProps,
  KaomojiWhatProps,
  KaomojiWhyProps,
} from "@/features/kaomoji/types";

import { withCanonical } from "@/lib/seo";

export const metadata: Metadata = {
  title: "ベイマックス顔文字一覧（Kaomoji）｜アスキーアート・シンプル・かわいいもコピペ",
  description:
    "ベイマックス顔文字（Kaomoji）をまとめて掲載。アスキーアート・シンプル・かわいい・表情豊か・動作・アクション・挨拶・ケアロボット・特殊・装飾まで。検索＆ワンクリックでコピーして、LINE/X（Twitter）/Instagram/Discordにそのままコピペ。登録不要で無料。スマホでもOK。",
  ...withCanonical("/baymax-kaomoji"),
};

export const baymaxKaomojiHeroContent: KaomojiHeroProps = {
  title: "ベイマックス顔文字一覧",
  kaomoji: "( ●－● )💙  ( ●－● )♡",
  subtitle: "アスキーアート・シンプルまで【コピペ簡単】",
  description:
    "「ベイマックスっぽさ」が出る顔文字を集めました。シンプルから可愛い系、装飾つき、ユニーク系まで幅広く掲載。気に入った顔文字はワンクリックでコピーして、そのまま貼り付けできます。",
  primaryCta: { href: "#list", label: "顔文字を探す" },
  secondaryCta: { href: "/", label: "ホームへ" },
};

export const baymaxKaomojiWhatContent: KaomojiWhatProps = {
  heading: "ベイマックス顔文字（Kaomoji）とは？",
  intro:
    "ベイマックス顔文字は、記号や絵文字、キャラっぽいパーツを組み合わせて「ベイマックス」の雰囲気を表現するKaomojiです。短い一言でもテーマが伝わりやすく、SNSやチャットのリアクションに便利です。",
  usageHeading: "使えるシーン",
  usageItems: [
    "ベイマックスの話題に",
    "挨拶や日常の返信に",
    "SNS投稿のテーマに",
    "かわいく盛りたいときに",
    "ネタやユニークな一言に",
  ],
  typesHeading: "ベイマックス顔文字の種類",
  types: [
    {
      title: "アスキーアート",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: (●―●) ∩ / ⌒ヽ （人＿__つ_つ  ( •ー• ) / つ と\\ ( ) \\　ﾉ \\ / ︶ ︶",
    },
    {
      title: "シンプル",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ( ●－● )💙  ( ●−● )",
    },
    {
      title: "かわいい",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ( ●－● )♡  （ ○－○ ）✩⡱",
    },
    {
      title: "表情豊か",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ( ✧ー✧) ｶｯ!!✨  (•﹏•)",
    },
    {
      title: "動作・アクション",
      description: "このカテゴリの定番をまとめてチェック。",
      example: "例: ＼( ●−● )／💪  ( ●-● )ノ ﾊﾞﾗﾗﾗﾗﾗﾝ♪",
    },
  ],
  featuresHeading: "ベイマックスらしさが出るポイント",
  features: [
    { symbol: "( ●－● )💙", title: "定番", description: "まずは短くて使いやすい定番から。" },
    { symbol: "♡", title: "かわいい", description: "かわいい系のカテゴリを選ぶと柔らかい印象に。" },
    { symbol: "✨", title: "装飾", description: "絵文字や装飾つきは投稿で映えます。" },
    { symbol: "ASCII", title: "AA/アート", description: "大きめの表現はネタとして強いです。" },
  ],
};

export const baymaxKaomojiWhyContent: KaomojiWhyProps = {
  heading: "ベイマックス顔文字の使い分け",
  subheading: "シンプルから装飾まで。場面に合わせて“雰囲気”を調整できます。",
  guideHeading: "シーン別ガイド",
  guides: [
    {
      title: "日常の返信",
      bullets: ["短めのシンプル系が自然", "文章に馴染みやすい"],
      recommend: "おすすめ: ( ●－● )💙",
    },
    {
      title: "SNS投稿",
      bullets: ["装飾つきでテーマが伝わりやすい", "写真と合わせると映える"],
      recommend: "おすすめ: ( ●－● )♡",
    },
    {
      title: "ネタ・ユニーク",
      bullets: ["ユニーク/AA系でインパクト", "使いすぎると読みにくいので注意"],
      recommend: "おすすめ: (●―●) ∩ / ⌒ヽ （人＿__つ_つ",
    },
    {
      title: "かわいく盛る",
      bullets: ["可愛いカテゴリを選ぶ", "一言に添えると収まりが良い"],
      recommend: "おすすめ: ( ●－● )♡",
    },
  ],
  cultureHeading: "「ベイマックス」モチーフは一言で伝わる",
  cultureBody:
    "ベイマックスは見た目のイメージが強く、短い文章でもテーマが伝わりやすいモチーフです。顔文字を添えるだけで、投稿や返信の雰囲気を軽く・かわいく・面白く調整できます。",
  cultureCards: [
    { title: "雰囲気", description: "テーマが一目で伝わる。" },
    { title: "リアクション", description: "一言に感情を足せる。" },
    { title: "盛れる", description: "装飾や絵文字で映える。" },
  ],
  tipsHeading: "すぐ使える例文",
  tips: [
    {
      title: "一言に添える",
      body: "短文 + 顔文字が使いやすいです。",
      example: "例: 今日はいい日 ( ●－● )💙",
    },
    {
      title: "投稿のテーマ",
      body: "写真や話題に合わせて選ぶと伝わりやすい。",
      example: "例: ベイマックスかわいい ( ●－● )♡",
    },
  ],
};

export const baymaxKaomojiFaqContent: KaomojiFaqProps = {
  heading: "よくある質問（FAQ）",
  subheading: "ベイマックス顔文字、迷ったらここだけ見ればOK。",
  items: [
    {
      question: "ベイマックス顔文字はどうやってコピーできますか？",
      answer:
        "一覧から好きな顔文字をクリックするとコピーできます。あとはLINEやSNSなどに貼り付けるだけです。",
    },
    {
      question: "文字化けしにくいのはどれ？",
      answer:
        "環境によっては絵文字や特殊文字の見え方が変わることがあります。心配なときは、記号中心のシンプル系を選ぶと安心です。",
    },
    {
      question: "タグは何のためにありますか？",
      answer:
        "検索用の目印です。気分や用途（かわいい/動作/ユニーク など）で絞り込んで探せます。",
    },
  ],
};

export const baymaxKaomojiGroups: KaomojiCollectionGroup[] = [
  {
    title: "アスキーアート",
    items: [
      { kaomoji: "   (●―●) ∩\n　/　　⌒ヽ\n（人＿__つ_つ", tags: ["アスキーアート","座る","大きい"] },
      { kaomoji: "  　( •ー• )\n　 / つ 　と\\\n　(　　　  　)\n　 \\　ﾉ \\ 　/\n　　︶    ︶", tags: ["アスキーアート","立つ","シンプル"] },
      { kaomoji: "    ' ( ⚫︎ー⚫︎ )\n   　／　　　  ＼\n   '/　　　　　 \\\n  /　/ 　　　 ヽ　\\\n |　/　 　　　 \\　|\n   \\Ԏ　　　　　 Ԏ/\n    卜−　　 ― イ\n    \\　　/\\　　ﾉ\n　   \\　ﾉ '\\　 /\n　　  ︶ 　 ︶", tags: ["アスキーアート","全身","大きい"] },
    ],
  },
  {
    title: "シンプル",
    items: [
      { kaomoji: "( ●－● )💙", tags: ["基本","ベイマックス"] },
      { kaomoji: "( ●−● )", tags: ["基本","定番"] },
      { kaomoji: "(●―●)🤍", tags: ["基本","ハート"] },
      { kaomoji: "( ⚫︎ー⚫︎ )", tags: ["基本","シンプル"] },
      { kaomoji: "(•ー•)✨", tags: ["基本","キラキラ"] },
      { kaomoji: "( ○－○ )", tags: ["基本","丸い"] },
      { kaomoji: "( ○━○ )", tags: ["基本","横線"] },
      { kaomoji: "(･ー･)", tags: ["基本","小さい"] },
      { kaomoji: "( ꕹ )", tags: ["基本","特殊記号"] },
      { kaomoji: "(   ꕹ   )", tags: ["基本","ゆったり"] },
      { kaomoji: "(   ●━●   )", tags: ["基本","広い"] },
      { kaomoji: "(•－•)", tags: ["基本","小さい目"] },
      { kaomoji: "（ ╾╼ ）", tags: ["基本","線目"] },
      { kaomoji: "( ･─･ )", tags: ["基本","細い"] },
      { kaomoji: "（ ●ー● ）", tags: ["基本","定番"] },
      { kaomoji: "( ☻灬☻ )", tags: ["基本","絵文字風"] },
      { kaomoji: "( ☻-☻ )", tags: ["基本","スマイリー"] },
      { kaomoji: "(●ー●)", tags: ["基本","コンパクト"] },
      { kaomoji: "（ˊ－ˋ）", tags: ["基本","穏やか"] },
      { kaomoji: "（ˇ－ˇ）", tags: ["基本","落ち着き"] },
      { kaomoji: "（ ֊－֊）", tags: ["基本","優しい"] },
      { kaomoji: "( ○ー○ )", tags: ["基本","丸目"] },
      { kaomoji: "( •─• )", tags: ["基本","細目"] },
      { kaomoji: "( ⊙ー⊙ )", tags: ["基本","大きい目"] },
      { kaomoji: "( ◎－◎ )", tags: ["基本","二重丸"] },
      { kaomoji: "( ●ᵕ●)", tags: ["笑顔","優しい"] },
      { kaomoji: "( ●´ー`●)", tags: ["穏やか","満足"] },
    ],
  },
  {
    title: "かわいい",
    items: [
      { kaomoji: "( ●－● )♡", tags: ["可愛い","ハート"] },
      { kaomoji: "（ ○－○ ）✩⡱", tags: ["可愛い","キラキラ"] },
      { kaomoji: "(*●−●*)💕", tags: ["可愛い","照れる"] },
      { kaomoji: "(灬•ー•灬)♡", tags: ["可愛い","ほっぺ"] },
      { kaomoji: "(๑•ー•๑)•*¨*•.¸¸♪", tags: ["可愛い","音符"] },
      { kaomoji: "✲ﾟ｡.(•ー•)ﾉ☆.｡₀:*ﾟ✲ﾟ*:₀｡", tags: ["可愛い","キラキラ"] },
      { kaomoji: "(*•ー•*).｡.:*♡", tags: ["可愛い","ハート"] },
      { kaomoji: ":*:・(*•ー•pq゛", tags: ["可愛い","おねだり"] },
      { kaomoji: "(๑•̆ー•̆)", tags: ["可愛い","困り顔"] },
      { kaomoji: "(•ᴗ•)♡", tags: ["可愛い","にっこり"] },
      { kaomoji: "( ●－● )♥", tags: ["可愛い","ハート"] },
      { kaomoji: "( ●－● )ﾉﾟ✧", tags: ["可愛い","魔法"] },
      { kaomoji: "(灬●ω●灬)♡", tags: ["可愛い","ほっぺ"] },
      { kaomoji: "ﾟ･*:.｡.(●ー●).｡.:*･ﾟ", tags: ["可愛い","装飾"] },
      { kaomoji: "♡( ●－● )♡", tags: ["可愛い","ダブルハート"] },
      { kaomoji: "(●´ー`●)♡", tags: ["可愛い","照れ"] },
      { kaomoji: "( ●－● )ﾉ♡", tags: ["可愛い","手を振る"] },
      { kaomoji: "(*•ω•*)ﾉ♡", tags: ["可愛い","挨拶"] },
      { kaomoji: "♪( ●ー● )♪", tags: ["可愛い","音符"] },
      { kaomoji: "✿( ●－● )✿", tags: ["可愛い","花"] },
      { kaomoji: "🌸( ●－● )🌸", tags: ["可愛い","桜"] },
      { kaomoji: "( ●－● )🎀", tags: ["可愛い","リボン"] },
      { kaomoji: "🎀( ●ー● )🎀", tags: ["可愛い","リボン"] },
      { kaomoji: "( ●ー● )💗", tags: ["可愛い","ピンクハート"] },
      { kaomoji: "✧( ●－● )✧", tags: ["可愛い","輝き"] },
      { kaomoji: "( ●_●)💙", tags: ["無表情","ハート"] },
      { kaomoji: "( ●ε●)", tags: ["チュー","口"] },
      { kaomoji: "( ●∀●)✨", tags: ["笑顔","嬉しい"] },
      { kaomoji: "( ●≧●)💖", tags: ["照れ","嬉しい"] },
      { kaomoji: "( ●⌒●)♪", tags: ["にっこり","音符"] },
    ],
  },
  {
    title: "表情豊か",
    items: [
      { kaomoji: "( ✧ー✧) ｶｯ!!✨", tags: ["キラキラ","驚き"] },
      { kaomoji: "(•﹏•)", tags: ["困惑","心配"] },
      { kaomoji: "( ;●−●; )💦", tags: ["泣く","悲しい"] },
      { kaomoji: "∑ ( ●−●//", tags: ["照れる","恥ずかしい"] },
      { kaomoji: "(´•ー•｀)", tags: ["穏やか","優しい"] },
      { kaomoji: "( ;●-●; )", tags: ["泣く","涙"] },
      { kaomoji: "(/ー＼)💫", tags: ["恥ずかしい","照れ"] },
      { kaomoji: "( ●−● )💢", tags: ["怒り","イライラ"] },
      { kaomoji: "( ●−● )💤", tags: ["眠い","睡眠"] },
      { kaomoji: "( ●−● )💭", tags: ["考える","思考"] },
      { kaomoji: "( ●ー● )？", tags: ["疑問","はてな"] },
      { kaomoji: "( ●ー● )！", tags: ["驚き","びっくり"] },
      { kaomoji: "(⌍●−●⌌)ｴﾈﾙｷﾞｰｶﾞ...", tags: ["電池切れ","疲労"] },
      { kaomoji: "( ●−● )ｵｺﾀﾞﾖ！", tags: ["怒る","プンプン"] },
      { kaomoji: "( ●−● )ｺﾞﾗｰ!", tags: ["怒る","叫ぶ"] },
      { kaomoji: "( ●−● )激おこﾌﾟﾝﾌﾟﾝ丸", tags: ["怒る","激怒"] },
      { kaomoji: "( ●−● )ｴｯ､ﾏｼﾞ？！！！", tags: ["驚き","マジ"] },
      { kaomoji: "( ; ●-●)", tags: ["汗","焦り"] },
      { kaomoji: "( ●−● )💧", tags: ["汗","困る"] },
      { kaomoji: "( ●＾●＾● )", tags: ["笑顔","嬉しい"] },
      { kaomoji: "( ●ω● )♪", tags: ["ご機嫌","ルンルン"] },
      { kaomoji: "( ●´д`●)", tags: ["困惑","ショック"] },
      { kaomoji: "( ●°ー°●)", tags: ["真顔","ポカーン"] },
      { kaomoji: "( ●-●💧)", tags: ["涙目","悲しい"] },
      { kaomoji: "( ●＞ー＜●)", tags: ["痛い","我慢"] },
      { kaomoji: "( ●̀ω●́)", tags: ["怒り","むっ"] },
      { kaomoji: "( ●△●)", tags: ["驚き","口開け"] },
      { kaomoji: "( ●□●)", tags: ["驚愕","びっくり"] },
      { kaomoji: "( ●︿●)", tags: ["悲しい","困る"] },
      { kaomoji: "( ●ヮ●)", tags: ["大喜び","興奮"] },
      { kaomoji: "( ●▽●)", tags: ["喜び","笑う"] },
      { kaomoji: "( ●皿●)", tags: ["ニヤリ","企み"] },
      { kaomoji: "( ●´∀`●)", tags: ["笑顔","楽しい"] },
    ],
  },
  {
    title: "動作・アクション",
    items: [
      { kaomoji: "＼( ●−● )／💪", tags: ["バンザイ","元気"] },
      { kaomoji: "( ●-● )ノ ﾊﾞﾗﾗﾗﾗﾗﾝ♪", tags: ["挨拶","歌"] },
      { kaomoji: "ε=ε=( ●−● )💨", tags: ["走る","急ぐ"] },
      { kaomoji: "⊂(●−●⊂ )))Σ≡=─ﾋﾞｭｰｰｰｰﾝ", tags: ["飛ぶ","ロケット"] },
      { kaomoji: "o( ●−● )oﾜｰｲ♪", tags: ["喜ぶ","バンザイ"] },
      { kaomoji: "v( ●−● )ｨｪｨ♪✌️", tags: ["ピース","イエイ"] },
      { kaomoji: "b( ●−● )👍", tags: ["グッド","いいね"] },
      { kaomoji: "ﾀﾞｯｼｭ!ε＝ε＝ε＝ε＝ε＝( ●−● )", tags: ["ダッシュ","走る"] },
      { kaomoji: "ε=ε=( ●−● )ノ　ｽﾞﾍﾞｯ(ﾉ●−● )ﾉ", tags: ["転ぶ","コケる"] },
      { kaomoji: "( ●−● )=====〇 ﾊﾞﾝﾁ!!", tags: ["パンチ","攻撃"] },
      { kaomoji: "( ●−● )=====〇壁ﾄﾞﾝｯ!!!", tags: ["壁ドン","アクション"] },
      { kaomoji: "\\(⚫︎ー⚫︎)/🙌", tags: ["バンザイ","喜び"] },
      { kaomoji: "╭(●ー●)و", tags: ["ガッツポーズ","やる気"] },
      { kaomoji: "(੭ •ー•)੭ु⁾⁾", tags: ["ジタバタ","動く"] },
      { kaomoji: "٩(๑•ー•๑)۶", tags: ["バンザイ","万歳"] },
      { kaomoji: "٩(๑`•ー•´๑)۶💪", tags: ["ガッツ","強い"] },
      { kaomoji: "☆♫ ٩(•ー•)۶♫ ★", tags: ["踊る","音楽"] },
      { kaomoji: "(╭☞•ー•)╭☞👉", tags: ["指差し","からの？"] },
      { kaomoji: "( ●−● )ゞﾗｼﾞｬ!!", tags: ["敬礼","了解"] },
      { kaomoji: "( ●−● )ゞ🫡", tags: ["敬礼","はい"] },
      { kaomoji: "( ●−● )ﾉﾞ ﾌｧｲﾄｫ～♪", tags: ["ファイト","応援"] },
      { kaomoji: "( ●−● )ノ🖐️", tags: ["手を振る","バイバイ"] },
      { kaomoji: "( ●−● )人(・∀・) ﾊﾞﾙｽ!!", tags: ["バルス","コラボ"] },
      { kaomoji: "( ●−● )👊ﾊﾞｷﾞ", tags: ["パンチ","強い"] },
      { kaomoji: "ヾ( ●−● )ノ🎉", tags: ["祝う","パーティー"] },
      { kaomoji: "＼( ●∀● )／🎊", tags: ["万歳","祝い"] },
      { kaomoji: "( ●-●)っ🎁", tags: ["プレゼント","渡す"] },
      { kaomoji: "( ●-●)っ🍰", tags: ["ケーキ","どうぞ"] },
      { kaomoji: "( ●-●)っ☕", tags: ["コーヒー","差し出す"] },
      { kaomoji: "( ●−● )〜♫", tags: ["歌う","音楽"] },
      { kaomoji: "( ●−● )📱", tags: ["スマホ","連絡"] },
      { kaomoji: "( ●−● )💻", tags: ["パソコン","作業"] },
      { kaomoji: "( ●−● )🎮", tags: ["ゲーム","遊ぶ"] },
      { kaomoji: "( ●−● )📚", tags: ["本","読書"] },
      { kaomoji: "( ●−● )🎵", tags: ["音楽","聴く"] },
      { kaomoji: "( ●−● )🍜", tags: ["ラーメン","食事"] },
    ],
  },
  {
    title: "挨拶",
    items: [
      { kaomoji: "こんにちは、ベイマックスです( ●−● )💙", tags: ["挨拶","こんにちは"] },
      { kaomoji: "( ●−● )ﾉｵﾊｵﾊｵﾊ♪☀️", tags: ["おはよう","朝"] },
      { kaomoji: "( ●−● )Good☆Morning🌅", tags: ["おはよう","英語"] },
      { kaomoji: "( ●−● )وWake Up⏰", tags: ["起きる","目覚め"] },
      { kaomoji: "ベイマックス( ●−● )おやすみ🌙", tags: ["おやすみ","夜"] },
      { kaomoji: "( ●−● )ﾉ おつかれさま～💐", tags: ["お疲れ様","労い"] },
      { kaomoji: "( ●−● )ﾉ バイバイ👋", tags: ["バイバイ","さようなら"] },
      { kaomoji: "ベイマックスです( ●−● )よろしく🤝", tags: ["よろしく","初めまして"] },
      { kaomoji: "( ●−● )いらっしゃい✨", tags: ["いらっしゃい","歓迎"] },
      { kaomoji: "ﾍﾞｲﾏｯｸｽ( ●−● )ただいま🏠", tags: ["ただいま","帰宅"] },
      { kaomoji: "( ●−● )おかえり～🏡", tags: ["おかえり","帰宅"] },
      { kaomoji: "ベイマックス( ●−● )ありがとう🙏", tags: ["ありがとう","感謝"] },
      { kaomoji: "( ●−● )ごめんね💦", tags: ["ごめん","謝罪"] },
      { kaomoji: "ﾍﾞｲﾏｯｸｽ( ●−● )がんばって💪", tags: ["がんばれ","応援"] },
      { kaomoji: "( ●−● )お大事に🏥", tags: ["お大事に","体調"] },
      { kaomoji: "ベイマックス( ●−● )元気？🌟", tags: ["元気","挨拶"] },
      { kaomoji: "( ●−● )久しぶり～👋", tags: ["久しぶり","再会"] },
      { kaomoji: "( ●−● )おめでとう🎊", tags: ["おめでとう","祝福"] },
      { kaomoji: "( ●−● )誕生日おめでとう🎂", tags: ["誕生日","祝い"] },
      { kaomoji: "( ●−● )いただきます🍽️", tags: ["いただきます","食事"] },
      { kaomoji: "( ●−● )ごちそうさま😋", tags: ["ごちそうさま","食後"] },
      { kaomoji: "( ●−● )いってきます🚶", tags: ["いってきます","出発"] },
      { kaomoji: "( ●−● )いってらっしゃい👋", tags: ["いってらっしゃい","送り出す"] },
      { kaomoji: "( ●−● )こんばんは🌃", tags: ["こんばんは","夜"] },
      { kaomoji: "( ●−● )またね～👋", tags: ["またね","別れ"] },
    ],
  },
  {
    title: "ケアロボット",
    items: [
      { kaomoji: "( ●−● )💉ワクチン接種完了", tags: ["医療","ワクチン"] },
      { kaomoji: "( ●−● )🩺健康診断", tags: ["診断","健康"] },
      { kaomoji: "( ●−● )体調はいかがですか？", tags: ["ケア","質問"] },
      { kaomoji: "( ●−● )🌡️体温測定中", tags: ["体温","測定"] },
      { kaomoji: "( ●−● )お薬の時間です💊", tags: ["薬","時間"] },
      { kaomoji: "( ●−● )大丈夫？❤️‍🩹", tags: ["心配","ケア"] },
      { kaomoji: "( ●−● )ゆっくり休んでね🛏️", tags: ["休養","睡眠"] },
      { kaomoji: "( ●−● )水分補給💧", tags: ["水分","健康"] },
      { kaomoji: "( ●−● )🏥病院に行きましょう", tags: ["病院","診察"] },
      { kaomoji: "( ●−● )痛いところはありますか？", tags: ["痛み","診断"] },
      { kaomoji: "( ●−● )🩹絆創膏貼ります", tags: ["絆創膏","怪我"] },
      { kaomoji: "( ●−● )ストレス解消♨️", tags: ["ストレス","リラックス"] },
      { kaomoji: "( ●−● )🧘‍♀️深呼吸しましょう", tags: ["深呼吸","落ち着く"] },
      { kaomoji: "( ●−● )睡眠は大事です💤", tags: ["睡眠","健康"] },
      { kaomoji: "( ●−● )栄養バランス🥗", tags: ["栄養","食事"] },
      { kaomoji: "( ●−● )運動しましょう🏃", tags: ["運動","健康"] },
      { kaomoji: "( ●−● )手を洗いましょう🧼", tags: ["手洗い","衛生"] },
      { kaomoji: "( ●−● )マスク着用😷", tags: ["マスク","予防"] },
      { kaomoji: "( ●−● )お見舞い💐", tags: ["お見舞い","回復"] },
      { kaomoji: "( ●−● )お疲れを感知しました😴", tags: ["疲れ","検知"] },
      { kaomoji: "( ●−● )zzZ💤", tags: ["睡眠","眠い"] },
      { kaomoji: "ベイマックス( ●−● )🔋充電中", tags: ["充電","回復"] },
    ],
  },
  {
    title: "特殊・装飾",
    items: [
      { kaomoji: "( ●−● )( ●−● )( ●−● )", tags: ["連続","複数"] },
      { kaomoji: "ﾍﾞｲﾏｯｸｽ━━( ●−● )━━!!", tags: ["キター","登場"] },
      { kaomoji: "ｷﾀ━━━━(•ー•)━━━━!!", tags: ["キター","興奮"] },
      { kaomoji: "ｺﾈ━━━━(•～•‵)━━━━!!", tags: ["コネー","残念"] },
      { kaomoji: "|ー•)ﾁﾗｯ", tags: ["チラッ","覗く"] },
      { kaomoji: "( •～•‵)ŧ‹\"ŧ‹\"ŧ‹\"ŧ‹\"", tags: ["食べる","もぐもぐ"] },
      { kaomoji: "(ﾉ≧ڡ•)てへぺろ", tags: ["てへぺろ","照れ"] },
      { kaomoji: "\\=͟͟͞͞(๑•̀=͟͟͞͞(๑•̀ー•́๑)", tags: ["連続","移動"] },
      { kaomoji: "( ●−● )( ;●−● )", tags: ["変化","焦り"] },
      { kaomoji: "【ベイマックス( ●−● )】", tags: ["枠","強調"] },
      { kaomoji: "《( ●−● )》", tags: ["枠","装飾"] },
      { kaomoji: "★( ●−● )★", tags: ["星","装飾"] },
      { kaomoji: "♪～( ●−● )～♪", tags: ["音符","ルンルン"] },
      { kaomoji: "≪( ●−● )≫", tags: ["記号","強調"] },
      { kaomoji: "∴( ●−● )∴", tags: ["記号","特殊"] },
      { kaomoji: "彡( ●−● )彡", tags: ["動き","スピード"] },
      { kaomoji: "⊂( ●−● )⊃", tags: ["抱きしめ","ハグ"] },
      { kaomoji: "┗( ●−● )┛", tags: ["台座","安定"] },
      { kaomoji: "╰( ●−● )╯", tags: ["両手","バンザイ"] },
      { kaomoji: "( ●−● )σ)", tags: ["指差し","突っ込み"] },
      { kaomoji: "🌈( ●−● )🌈", tags: ["虹","希望"] },
      { kaomoji: "🌟( ●−● )🌟", tags: ["星","輝き"] },
    ],
  },
];

